---
# *************************************************************************************************************************************************
# --------------------------------------------------------------------------------------------------------------------------------------
# IBMAIOPS INSTANCES
# --------------------------------------------------------------------------------------------------------------------------------------
# *************************************************************************************************************************************************


global_config:
  environment_name: ibmaiops
  cloud_platform: existing-ocp
  # --------------------------------------------------------------------------------------------------------------------------------------
  # IBMAIOPS Pull Registires
  # --------------------------------------------------------------------------------------------------------------------------------------
  entitled_registry: cp.icr.io
  entitled_registry_user: cp
  catalog_image: icr.io/cpopen/ibm-operator-catalog:latest
  # Create Welcome Cards in IBMAIOps
  create_cards: true
  # Create App Menu Items in OCP
  create_ocp_items: true
  # Use this Password for all Instances
  global_password: P4ssw0rd!
  # Set this value to True to accept all licenses
  accept_all_licenses: False
  # Create Notifications in OCP
  create_ocp_notifications: true
  position_ocp_notifications: BannerTop
  position_final_ocp_notification: BannerTop
  # Key to decrypt Licenses
  # license_token: NONE


openshift:
- name: "mycluster"
  ocp_version: "4.12"
  cluster_name: "mycluster"
  domain_name: example.com
  openshift_storage:
  - storage_name: auto-storage
    storage_type: auto
    # Alternatively use
    #storage_name: ibm-roks-storage
    #storage_type: custom
    #ocp_storage_class_file: ibmc-file-gold-gid
    #ocp_storage_class_block: ibmc-block-gold


ibmaiops:
- project: ibmaiops-addons
  instances:
  # --------------------------------------------------------------------------------------------------------------------------------------
  # IBMAIOPS TURBONOMIC
  # --------------------------------------------------------------------------------------------------------------------------------------
  - name: ibmaiops-turbonomic
    kind: Turbonomic
    install: true
    turbo_version: 8.8.3
    
    # --------------------------------------------------------------------------------------------------------------------------------------
    # Storage Classes Override for this Instance (see comment below)
    # --------------------------------------------------------------------------------------------------------------------------------------
    #storage_class_file: automatic
    #storage_class_block: automatic

    
  - name: ibmaiops-turbonomic-demo-content
    kind: TurbonomicDemoContent
    install: true
    # Admin User Password (OVERRIDES GLOBAL PASSWORD)
    #turbo_admin_password: P4ssw0rd!
    # ---------------------------------------------------------------------
    # Create Demo User
    create_user: true
    # Demo User Name
    demo_user: demo
    # Demo User Password (OVERRIDES GLOBAL PASSWORD)
    #turbo_demo_password: P4ssw0rd!
    # ---------------------------------------------------------------------
    # Create Groups
    group_vcenter_vms: true
    group_robotshop: true
    group_licensing: true

    # ---------------------------------------------------------------------
    # Create Targets
    target_instana: true
    # ---------------------------------------------------------------------
    # Create Memory and CPU hogs
    resource_hogs: true
    # ---------------------------------------------------------------------
    # Create Metrics server, DIF integration and RobotShop BuisnessApp
    metrics_dif: true
    # ---------------------------------------------------------------------
    # Turbo License (optional)
    turbo_license: NONE
    

# *************************************************************************************************************************************************
# --------------------------------------------------------------------------------------------------------------------------------------
# IBMAIOPS USAGE
# --------------------------------------------------------------------------------------------------------------------------------------
# *************************************************************************************************************************************************


# --------------------------------------------------------------------------------------------------------------------------------------
# IBMAIOPS Storage Classes
# --------------------------------------------------------------------------------------------------------------------------------------

# Override the Storage Class auto detection (not_configured, ibmc-file-gold-gid, rook-cephfs, nfs-client, ...)
#storage_class_file: automatic
#storage_class_file: ibmc-file-gold-gid               # ROKS
#storage_class_file: ocs-storagecluster-cephfs        # ODF
#storage_class_file: ibmc-vpc-block-10iops-tier       # IBM VPC
#storage_class_file: rook-cephfs                      # FYRE
#storage_class_file: nfs-client                       # TEC

#storage_class_block: automatic
#storage_class_block: ibmc-block-gold                 # ROKS
#storage_class_block: ocs-storagecluster-ceph-rbd     # ODF
#storage_class_block: ibmc-vpc-block-10iops-tier      # IBM VPC
#storage_class_block: rook-cephfs                     # FYRE
#storage_class_block: nfs-client                      # TEC

