---
# *************************************************************************************************************************************************
# --------------------------------------------------------------------------------------------------------------------------------------
# IBMAIOPS INSTANCES
# --------------------------------------------------------------------------------------------------------------------------------------
# *************************************************************************************************************************************************


global_config:
  environment_name: ibm-aiops
  cloud_platform: existing-ocp
  # --------------------------------------------------------------------------------------------------------------------------------------
  # IBMAIOPS Pull Registires
  # --------------------------------------------------------------------------------------------------------------------------------------
  entitled_registry: cp.icr.io
  entitled_registry_user: cp
  catalog_image: icr.io/cpopen/ibm-operator-catalog:latest
  # Create Welcome Cards in IBMAIOps
  create_cards: false
  # Create App Menu Items in OCP
  create_ocp_items: false
  # Use this Password for all Instances
  global_password: P4ssw0rd!
  # Set this value to True to accept all licenses
  accept_all_licenses: False
  # Create Notifications in OCP
  create_ocp_notifications: true
  position_ocp_notifications: BannerTop
  position_final_ocp_notification: BannerTop
  # Key to decrypt Licenses
  # license_token: NONE


openshift:
- name: "mycluster"
  ocp_version: "4.12"
  cluster_name: "mycluster"
  domain_name: example.com
  openshift_storage:
  - storage_name: auto-storage
    storage_type: auto
    # Alternatively use
    #storage_name: ibm-roks-storage
    #storage_type: custom
    #ocp_storage_class_file: ibmc-file-gold-gid
    #ocp_storage_class_block: ibmc-block-gold


ibm-aiops:
- project: ibm-aiops
  instances:
  # --------------------------------------------------------------------------------------------------------------------------------------
  # INSTALL IBMAIOPS
  # --------------------------------------------------------------------------------------------------------------------------------------
  - name: ibm-aiops
    kind: IBMAIOps
    install: false

    # current_ibm-aiops_feature
    # IBMAIOPS Size of the install (small: PoC/Demo, tall: Production)
    aiops_size: small
    # Custom Sizing File (aiops_size must be set to "custom")
    custom_size_file: none    # Name of the IBMAIOPS instance
    # Name of the IBMAIOPS instance
    aiops_name: ibm-cp-watson-aiops
    # Version of the catalog subscription
    subscription_channel: v3.7
    # Freeze the version of the Catalog image by patching CatalogSource
    freeze_catalog: false

    # --------------------------------------------------------------------------------------------------------------------------------------
    # Storage Classes Override for this Instance (see comment below)
    # --------------------------------------------------------------------------------------------------------------------------------------
    #storage_class_file: automatic
    #storage_class_block: automatic

    # --------------------------------------------------------------------------------------------------------------------------------------
    # Install with CASE Files
    # --------------------------------------------------------------------------------------------------------------------------------------
    case_install: false
    case_github_url: "https://github.com/IBM/cloud-pak/raw/master/repo/case"
    case_name: ibm-cp-aiops
    case_version: 1.5.0
    case_inventory_setup: cpaiopsSetup






  # --------------------------------------------------------------------------------------------------------------------------------------
  # INSTALL IBMAIOPS Demo Content
  # --------------------------------------------------------------------------------------------------------------------------------------
  - name: ibm-aiops-demo-content
    kind: IBMAIOpsDemoContent
    install: true


    # ---------------------------------------------------------------------
    # TRAINING
    # Train the Models based on pre-canned content

    training_create_training_temporal: false

    training_load_data_logs: false
    training_create_training_logs: false
    training_run_training_logs: false

    training_load_data_snow: false
    training_create_training_snow: false
    training_run_training_snow: false

    training_load_data_metrics: false
    training_create_training_metrics: false
    training_run_training_metrics: false

    training_data_url: https://github.com/niklaushirt/
    training_data_repo: ibm-aiops-trainingdata


    # ---------------------------------------------------------------------
    # TOPOLOGY
    # Install DemoApps Application
    install_demoapps: false
    # Install DemoApps K8s Observer
    install_demoapps_observer: false
    # Create Topology
    create_topology_templates: false
    create_topology_apps: false
    # Create Custom overlay topology
    install_custom_topology: false


    # ---------------------------------------------------------------------
    # RUNBOOKS
    # Install AWX and create Runbooks
    install_awx: false
    load_awx_playbooks: false
    integrate_awx: false
    load_runbooks: false
    create_runbook_policy: false


    # ---------------------------------------------------------------------
    # Demo UI
    install_demo_ui: false
    demoui_slack_url: https://aiopsdemohq.slack.com/sign_in_with_password
    # demoui_slack_url: https://aiops-fry2953.slack.com/x-p1624757694871-3716524482480-3705437209041/messages/C01JZLFJFMJ
    demoui_slack_user: ibm-aiopsdemo@gmail.com
    demoui_slack_pwd: P4ssw0rd!
    demoui_admin_mode: "true"
    demoui_simulation_mode: "true"

    demoui_user: demo
    # Password for the Demo UI (OVERRIDES GLOBAL PASSWORD)
    #demoui_pwd: P4ssw0rd!


    # ---------------------------------------------------------------------
    # LDAP
    install_ldap: false
    # ldap domain
    ldap_domain: ibm.com
    # ldap base
    ldap_base: dc=ibm,dc=com
    # LDAP Admin Password (OVERRIDES GLOBAL PASSWORD)
    #ldap_admin_password: P4ssw0rd!
    # LDAP Password for all Users (OVERRIDES GLOBAL PASSWORD)
    #ldap_user_password: P4ssw0rd!
    # ldap namespace
    ldap_namespace: openldap
    # ldap namespace
    ldap_register: false

    # ---------------------------------------------------------------------
    # MISC PARAMETERS (you should not modify those)
    # Create external routes (needed to create demo content)
    create_external_routes: false

    # Create a valid ingress certificate (needed for Slack integration)
    create_valid_ingress_certificate: false

    # Create Policy for Incident Creation
    create_incident_policy: false

    # Create Kafka connection for Log inception (needed to create log anomalies in the demo environment)
    create_log_connection: false

    # Create Service Account
    create_account: false

    # Install Webhook Probe
    install_webhook_probe: false

    # ---------------------------------------------------------------------
    # OUTPUT
    # Print all logins
    print_logins: false
    # Open the relevant Web UIs
    open_web_ui: false





- project: ibm-aiops-evtmgr
  instances:
  # --------------------------------------------------------------------------------------------------------------------------------------
  # IBMAIOPS Event Manager
  # --------------------------------------------------------------------------------------------------------------------------------------
  - name: ibm-aiops-eventmanager
    kind: EventManager
    install: false
    # Version of the catalog subscription
    subscription_channel: v1.11
    starting_csv: noi.v1.7.0
    noi_version: 1.6.6

    # --------------------------------------------------------------------------------------------------------------------------------------
    # Storage Classes Override for this Instance (see comment below)
    # --------------------------------------------------------------------------------------------------------------------------------------
    #storage_class_file: automatic
    #storage_class_block: automatic
    

  # --------------------------------------------------------------------------------------------------------------------------------------
  # IBMAIOPS Event Manager Demo Content
  # --------------------------------------------------------------------------------------------------------------------------------------
  - name: ibm-aiops-eventmanager
    kind: EventManagerDemoContent
    install: false




- project: ibm-aiops-infra
  instances:
  # --------------------------------------------------------------------------------------------------------------------------------------
  # IBMAIOPS Infrastructure Management
  # --------------------------------------------------------------------------------------------------------------------------------------
  - name: ibm-aiops-infrastructure-management
    kind: InfrastructureManagement
    install: false
    # Version of the catalog subscription
    subscription_channel: v3.7
    # Freeze the version of the Catalog image by patching CatalogSource
    freeze_catalog: false
    
    
    # --------------------------------------------------------------------------------------------------------------------------------------
    # Storage Classes Override for this Instance (see comment below)
    # --------------------------------------------------------------------------------------------------------------------------------------
    #storage_class_file: automatic
    #storage_class_block: automatic
    



- project: ibm-aiops-addons
  instances:
  # --------------------------------------------------------------------------------------------------------------------------------------
  # IBMAIOPS ELK
  # --------------------------------------------------------------------------------------------------------------------------------------
  - name: ibm-aiops-elk
    kind: ELK
    install: false


  # --------------------------------------------------------------------------------------------------------------------------------------
  # IBMAIOPS INSTANA
  # --------------------------------------------------------------------------------------------------------------------------------------
  - name: ibm-aiops-instana
    kind: Instana
    install: false
    version: 241-3

    # ---------------------------------------------------------------------
    # INSTANA LICENSE
    sales_key: 'NONE'
    agent_key: 'NONE'

    # ---------------------------------------------------------------------
    # INSTANA ADMIN LOGIN
    # Admin User Name
    instana_admin_user: "admin@instana.local"
    # Admin User Password (OVERRIDES GLOBAL PASSWORD)
    #instana_admin_pass: 'P4ssw0rd!'
    
    # ---------------------------------------------------------------------
    # INSTALL INSTANA AGENT
    install_agent: false

    # --------------------------------------------------------------------------------------------------------------------------------------
    # INTEGRATIONS
    integrate_ibm-aiops: false
    #integrate_turbonomic: false
    
    # --------------------------------------------------------------------------------------------------------------------------------------
    # Storage Classes Override for this Instance (see comment below)
    # --------------------------------------------------------------------------------------------------------------------------------------
    #storage_class_file: automatic
    #storage_class_block: automatic

    

  # --------------------------------------------------------------------------------------------------------------------------------------
  # IBMAIOPS TURBONOMIC
  # --------------------------------------------------------------------------------------------------------------------------------------
  - name: ibm-aiops-turbonomic
    kind: Turbonomic
    install: false
    turbo_version: 8.8.3

    # --------------------------------------------------------------------------------------------------------------------------------------
    # Storage Classes Override for this Instance (see comment below)
    # --------------------------------------------------------------------------------------------------------------------------------------
    #storage_class_file: automatic
    #storage_class_block: automatic

  - name: ibm-aiops-turbonomic-demo-content
    kind: TurbonomicDemoContent
    install: false
    # Admin User Password (OVERRIDES GLOBAL PASSWORD)
    #turbo_admin_password: P4ssw0rd!
    # ---------------------------------------------------------------------
    # Create Demo User
    create_user: false
    # Demo User Name
    demo_user: demo
    # Demo User Password (OVERRIDES GLOBAL PASSWORD)
    #turbo_demo_password: P4ssw0rd!
    # ---------------------------------------------------------------------
    # Create Groups
    group_vcenter_vms: false
    group_robotshop: false
    group_licensing: false

    # ---------------------------------------------------------------------
    # Create Targets
    target_instana: false
    # ---------------------------------------------------------------------
    # Create Memory and CPU hogs
    resource_hogs: false
    # ---------------------------------------------------------------------
    # Create Metrics server, DIF integration and RobotShop BuisnessApp
    metrics_dif: false
    # ---------------------------------------------------------------------
    # Turbo License (optional)
    turbo_license: NONE

# *************************************************************************************************************************************************
# --------------------------------------------------------------------------------------------------------------------------------------
# IBMAIOPS USAGE
# --------------------------------------------------------------------------------------------------------------------------------------
# *************************************************************************************************************************************************


# --------------------------------------------------------------------------------------------------------------------------------------
# IBMAIOPS Storage Classes
# --------------------------------------------------------------------------------------------------------------------------------------

# Override the Storage Class auto detection (not_configured, ibmc-file-gold-gid, rook-cephfs, nfs-client, ...)
#storage_class_file: automatic
#storage_class_file: ibmc-file-gold-gid               # ROKS
#storage_class_file: ocs-storagecluster-cephfs        # ODF
#storage_class_file: ibmc-vpc-block-10iops-tier       # IBM VPC
#storage_class_file: rook-cephfs                      # FYRE
#storage_class_file: nfs-client                       # TEC

#storage_class_block: automatic
#storage_class_block: ibmc-block-gold                 # ROKS
#storage_class_block: ocs-storagecluster-ceph-rbd     # ODF
#storage_class_block: ibmc-vpc-block-10iops-tier      # IBM VPC
#storage_class_block: rook-cephfs                     # FYRE
#storage_class_block: nfs-client                      # TEC




