

#-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#         ________  __  ___     ___    ________       
#        /  _/ __ )/  |/  /    /   |  /  _/ __ \____  _____
#        / // __  / /|_/ /    / /| |  / // / / / __ \/ ___/
#      _/ // /_/ / /  / /    / ___ |_/ // /_/ / /_/ (__  ) 
#     /___/_____/_/  /_/    /_/  |_/___/\____/ .___/____/  
#                                           /_/
#-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#---------------------------------------------------------------------------------------------------------------------------------------------------"
#  Installing ArgoCD
#
#  IBM AIOps
#
#  ¬©2023 nikh@ch.ibm.com
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# Installs:
#
#  - ArgoCD
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
 


- name: ‚ú¥Ô∏è ‚ú¥Ô∏è ‚ú¥Ô∏è INSTALLATION MODULE START - {{current_ibmaiops_feature.kind}}
  debug: 
    msg: 
    - "***************************************************************************************************************************************************"
    - "***************************************************************************************************************************************************"
    - "***************************************************************************************************************************************************"
    - "***************************************************************************************************************************************************"
    - "                                                                                                                                                   "
    - "      üü°üü°üü°üü°üü°  üöÄ IBM AIOps - INSTALLING {{current_ibmaiops_feature.kind}} üü°üü°üü°üü°üü°                                                        "
    - "                                                                                                                                                   "
    - "***************************************************************************************************************************************************"
    - "***************************************************************************************************************************************************"
    - "***************************************************************************************************************************************************"




- name: üü£ Installing {{current_ibmaiops_feature.kind}} with the following configuration
  debug:
    var: current_ibmaiops_feature


# - name:  üü£ Installation Parameters"
#   debug:
#     msg:
#     - "** Installation Options ***********************************************************************"
#     - " Storage Class File Override:      {{ current_ibmaiops_feature.storage_class_file}}"
#     - " Storage Class Block Override:     {{ current_ibmaiops_feature.storage_class_block}}"
#     - " Storage Class InfraManagement:    {{ current_ibmaiops_feature.storage_class_file}}"
#     - ""


# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# INITIALIZATION
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# Placeholder for customization
- name: üì• Init Custom Hook
  include_tasks: 00_init-custom-hook.yaml

# Initialize Logging
- name: üì• Init Logging
  include_tasks: "{{role_path}}/../ibmaiops-global/tasks/01_init-logging.yaml"

# Start block
- name: üì• Start Logging
  include_tasks: "{{role_path}}/../ibmaiops-global/tasks/90-log-start.yaml"

# Run Prerequisites
- name: üì• Initialization
  include_tasks: 01_init-initialization.yaml
  





# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# INSTALL ARGOCD
# ---------------------------------------------------------------------------------------------------------------------------------------------------"

- name: üì• Install ArgoCD Instance
  include_tasks: 10_gitops-install.yaml
      



- name: üì• End Logging
  include_tasks: "{{role_path}}/../ibmaiops-global/tasks/91-log-end.yaml"






- name: ‚úÖ INSTALLATION MODULE DONE - {{current_ibmaiops_feature.kind}}
  debug: 
    msg: 

    - "***************************************************************************************************************************************************"
    - "***************************************************************************************************************************************************"
    - "***************************************************************************************************************************************************"
    - "***************************************************************************************************************************************************"
    - "                                                                                                                                                   "
    - "       ‚úÖ IBM AIOps - DONE INSTALLING {{current_ibmaiops_feature.kind}}                                                                                 "
    - "                                                                                                                                                   "
    - "***************************************************************************************************************************************************"
    - "***************************************************************************************************************************************************"
    - "***************************************************************************************************************************************************"
