# number of pods to be expected in final ibm-aiops namespace
aiops_ns_min_pods_final: 123

# Create externally accessible Route for Topology
create_topo_route: true

# Create externally accessible Routes  (security risk!)
# Flink
# IBMAIOps API Route
# Datalayer API ...
create_external_routes: true

# Link to documentation
url_doc: https://github.com/niklaushirt/ibm-aiops-deployer#3-ai-manager-configuration