
# *************************************************************************************************************************************************
# --------------------------------------------------------------------------------------------------------------------------------------
# Install ADDONS
# --------------------------------------------------------------------------------------------------------------------------------------
# *************************************************************************************************************************************************

# --------------------------------------------------------------------------------------------------------------------------------------
# Create OCP Demouser Account
# --------------------------------------------------------------------------------------------------------------------------------------

- name: ðŸ›°ï¸  START - CREATE USER
  debug: 
    msg="{{ lookup('pipe','date +%d.%m.%Y---%H:%M:%S') }}"


- name: Log
  shell: |
    export MESSAGE="Creating OCP User"
    export currentDate=$(date +%Y-%m-%d_%H:%M)
    echo "---------------------------------------------------------------------------------------------------------------------------------------------------" >> ../install_{{current_ ibm-aiops_feature.kind}}.log
    echo $currentDate" - "$MESSAGE  >> ../install_{{current_ ibm-aiops_feature.kind}}.log
  ignore_errors: true

- name: ðŸ“£ OCP CONSOLE - Create Openshift NOTIFICATION
  shell: |
    cat <<EOF | oc apply -f -
    apiVersion: console.openshift.io/v1
    kind: ConsoleNotification
    metadata:
      name: ibm-aiops-notification
    spec:
      backgroundColor: '#ffd500'
      color: '#000'
      location: {{global_config.position_ocp_notifications | default("BannerTop")}}
      text: 'Installing {{current_ ibm-aiops_feature.kind}} - Creating OCP User'    
    EOF
  ignore_errors: true
  when: global_config.create_ocp_notifications | default(true) == true  



- name: ðŸ‘©â€ðŸ’» DEMO USER - Check OCP Demouser Account
  shell: |
    oc get serviceaccount --ignore-not-found -n default demo-admin
  ignore_errors: true
  register: USER_EXISTS


- name: ðŸ‘©â€ðŸ’» DEMO USER - Create OCP Demouser Account
  shell: |
        oc project {{current_ibmaiops_cluster.project}} 
        oc create serviceaccount -n default demo-admin
        oc create clusterrolebinding test-admin --clusterrole=cluster-admin --serviceaccount=default:demo-admin
        oc create clusterrolebinding ibm-zen-operator-serviceaccount --clusterrole=cluster-admin --serviceaccount=ibm-common-services:ibm-zen-operator-serviceaccount
  ignore_errors: true
  register: demo_account
  when: USER_EXISTS.stdout|length == 0

