

#-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#         ________  __  ___     ___    ________       
#        /  _/ __ )/  |/  /    /   |  /  _/ __ \____  _____
#        / // __  / /|_/ /    / /| |  / // / / / __ \/ ___/
#      _/ // /_/ / /  / /    / ___ |_/ // /_/ / /_/ (__  ) 
#     /___/_____/_/  /_/    /_/  |_/___/\____/ .___/____/  
#                                           /_/
#-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#---------------------------------------------------------------------------------------------------------------------------------------------------"
#  Installing IBM AIOps
#
#  IBM AIOps
#
#  Â©2024 nikh@ch.ibm.com
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# Installs:
#
#  - AIOPS Operator
#  - Infrastructure Management (CAM, CloudForms)
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
 
 
 
- name:  ðŸŸ£ðŸŸ£ðŸŸ£ðŸŸ£ðŸŸ£ðŸŸ£  INSTALLATION MODULE START - {{current_ibmaiops_feature.kind}}
  debug: 
    msg: 
    - "***************************************************************************************************************************************************"
    - "***************************************************************************************************************************************************"
    - "***************************************************************************************************************************************************"
    - "***************************************************************************************************************************************************"
    - "                                                                                                                                                   "
    - "      ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡  ðŸš€ IBM AIOps - INSTALLING {{current_ibmaiops_feature.kind}} ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡                                                        "
    - "                                                                                                                                                   "
    - "***************************************************************************************************************************************************"
    - "***************************************************************************************************************************************************"
    - "***************************************************************************************************************************************************"

- name: ðŸ“£ OCP CONSOLE - Create Openshift NOTIFICATION
  shell: |
    export AIOPS_NAMESPACE=$(oc get po -A|grep aiops-orchestrator-controller |awk '{print$1}')
    appURL=$(oc get routes -n $AIOPS_NAMESPACE-demo-ui ibm-aiops-demo-ui  -o jsonpath="{['spec']['host']}")|| true

    cat <<EOF | oc apply -f -
    apiVersion: console.openshift.io/v1
    kind: ConsoleNotification
    metadata:
      name: ibm-aiops-notification
    spec:
      backgroundColor: '#141a6b'
      color: '#fff'
      location: {{global_config.position_ocp_notifications | default("BannerTop")}}
      text: 'Installing  {{current_ibmaiops_feature.kind}}'    
    EOF
  ignore_errors: true
  args:
    executable: /bin/bash


- name: ðŸŸ£ Installing {{current_ibmaiops_feature.kind}} with the following configuration
  debug:
    var: current_ibmaiops_feature


- name:  ðŸŸ£ Storage Class Parameters - SPECIFIC INSTANCE"
  debug:
    msg:
    - "** Installation Options for SPECIFIC INSTANCE ***********************************************************************"
    - " Storage Class File Override:      {{ current_ibmaiops_feature.storage_class_file}}"
    - " Storage Class Block Override:     {{ current_ibmaiops_feature.storage_class_block}}"
    - " Storage Class InfraManagement:    {{ current_ibmaiops_feature.storage_class_file}}"
    - ""
  when: current_ibmaiops_feature.storage_class_file is defined


- name:  ðŸŸ£ Storage Class Parameters - GLOBAL"
  debug:
    msg:
    - "** Installation Options from GLOBAL ***********************************************************************"
    - " Storage Class File Override:      {{ ocp_storage_class_file }}"
    - " Storage Class Block Override:     {{ ocp_storage_class_block }}"
    - " Storage Class InfraManagement:    {{ ocp_storage_class_file }}"
    - ""
  when: current_ibmaiops_feature.storage_class_file is not defined and ocp_storage_class_file is defined




# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# INITIALIZATION
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# Placeholder for customization
- name: ðŸŸ¡ðŸŸ¡ðŸŸ¡  00_init-custom-hook
  include_tasks: 00_init-custom-hook.yaml

# Initialize Logging
- name: ðŸŸ¡ðŸŸ¡ðŸŸ¡  01_init-logging
  include_tasks: "{{role_path}}/../ibm-aiops-global/tasks/01_init-logging.yaml"
    
- name: ðŸŸ¡ðŸŸ¡ðŸŸ¡  02_init_checks
  include_tasks: 02_init_checks.yaml
# Start block
- name: ðŸŸ¡ðŸŸ¡ðŸŸ¡  90-log-start
  include_tasks: "{{role_path}}/../ibm-aiops-global/tasks/90-log-start.yaml"

  

- name: ðŸŸ¡ðŸŸ¡ðŸŸ¡  05_init-get-storage-class
  include_tasks: "{{role_path}}/../ibm-aiops-global/tasks/05_init-get-storage-class.yaml"
      


# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# INSTALL INFRA MANAGEMENT
# ---------------------------------------------------------------------------------------------------------------------------------------------------"

# Install  Instance
- name: ðŸŸ¡ðŸŸ¡ðŸŸ¡  16_inframanagement-install
  include_tasks: 16_inframanagement-install.yaml
      

# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# INSTALL ADDONS
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# Install OpenLDAP
- name: ðŸŸ¡ðŸŸ¡ðŸŸ¡  21_addons-ldap
  include_tasks: 21_addons-ldap.yaml
# Create Service Accoutn and USER
- name: ðŸŸ¡ðŸŸ¡ðŸŸ¡   22_addons-user
  include_tasks: 22_addons-user.yaml


# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# WAIT FOR INSTALLATION READY
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# Wait for Common Services being completely installed
- name: ðŸŸ¡ðŸŸ¡ðŸŸ¡  99_aimanager-wait-common-services
  include_tasks: 99_aimanager-wait-common-services.yaml



# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# POSTINSTALL TASKS
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# Register LDAP Users
- name: ðŸŸ¡ðŸŸ¡ðŸŸ¡  25-post-ldap-register
  include_tasks: 25-post-ldap-register.yaml
      



- name: ðŸŸ¡ðŸŸ¡ðŸŸ¡  91-log-end
  include_tasks: "{{role_path}}/../ibm-aiops-global/tasks/91-log-end.yaml"




- name:  ðŸŸ£ðŸŸ£ðŸŸ£ðŸŸ£ðŸŸ£ðŸŸ£  âœ… INSTALLATION MODULE DONE - {{current_ibmaiops_feature.kind}}
  debug: 
    msg:  

    - "***************************************************************************************************************************************************"
    - "***************************************************************************************************************************************************"
    - "***************************************************************************************************************************************************"
    - "***************************************************************************************************************************************************"
    - "                                                                                                                                                   "
    - "       âœ… IBM AIOps - DONE INSTALLING {{current_ibmaiops_feature.kind}}                                                                                 "
    - "                                                                                                                                                   "
    - "***************************************************************************************************************************************************"
    - "***************************************************************************************************************************************************"
    - "***************************************************************************************************************************************************"
