

#-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#     ________  __  ___   __________    ___         __                        __  _
#    /  _/ __ )/  |/  /  /  _/_  __/   /   | __  __/ /_____  ____ ___  ____ _/ /_(_)___  ____
#    / // __  / /|_/ /   / /  / /     / /| |/ / / / __/ __ \/ __ `__ \/ __ `/ __/ / __ \/ __ \
#  _/ // /_/ / /  / /  _/ /  / /     / ___ / /_/ / /_/ /_/ / / / / / / /_/ / /_/ / /_/ / / / /
# /___/_____/_/  /_/  /___/ /_/     /_/  |_\__,_/\__/\____/_/ /_/ /_/\__,_/\__/_/\____/_/ /_/
#
#-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#---------------------------------------------------------------------------------------------------------------------------------------------------"
#  Installing IBM AIOps
#
#  IBM AIOps
#
#  Â©2024 nikh@ch.ibm.com
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# Installs:
#
#  - Turbonomic
#  - Turbonomic Demo Content
#     - Demo User
#     - RobotShop Demo App with synthetic metric
#     - Instana target (if Instana is installed - you have to enter the API Token Manually)
#     - Groups for vCenter and RobotShop
#     - Groups for licensing
#     - Resource Hogs
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
 
 
 
- name: ðŸŸ£ðŸŸ£ðŸŸ£ðŸŸ£ðŸŸ£ðŸŸ£  INSTALLATION MODULE START - {{current_feature.kind}}
  debug: 
    msg: 
    - "***************************************************************************************************************************************************"
    - "***************************************************************************************************************************************************"
    - "***************************************************************************************************************************************************"
    - "***************************************************************************************************************************************************"
    - "                                                                                                                                                   "
    - "      ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡  ðŸš€ IBM IT Automation - INSTALLING {{current_feature.kind}} ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡                                                        "
    - "                                                                                                                                                   "
    - "***************************************************************************************************************************************************"
    - "***************************************************************************************************************************************************"
    - "***************************************************************************************************************************************************"

- name: ðŸ“£ OCP CONSOLE - Create Openshift NOTIFICATION
  shell: |
    export AIOPS_NAMESPACE=$(oc get po -A|grep aiops-orchestrator-controller |awk '{print$1}')
    appURL=$(oc get routes -n $AIOPS_NAMESPACE-demo-ui ibm-aiops-demo-ui  -o jsonpath="{['spec']['host']}")|| true
    OPENSHIFT_ROUTE=$(oc get route -n openshift-console console -o jsonpath={.spec.host})    

    cat <<EOF | oc apply -f -
    apiVersion: console.openshift.io/v1
    kind: ConsoleNotification
    metadata:
      name: ibm-aiops-notification-main
    spec:
      backgroundColor: '#141a6b'
      color: '#fff'
      location: {{global_config.position_final_ocp_notification | default("BannerBottom")}}
      text: 'Installing  {{current_feature.kind}} - '    
      link:
          href: "https://$OPENSHIFT_ROUTE/k8s/ns/ibm-installer/pods/$INSTALL_POD/logs"
          text: Open Logs  
    EOF
  ignore_errors: true
  args:
    executable: /bin/bash

# *************************************************************************************************************************************************
# --------------------------------------------------------------------------------------------------------------------------------------
# Check Login
# --------------------------------------------------------------------------------------------------------------------------------------
# *************************************************************************************************************************************************
- name:   ðŸš€ INITIALIZATION - Get Cluster FQDN
  shell: |
    CLUSTER_ROUTE=$(oc get routes console -n openshift-console | tail -n 1 2>&1 ) 
    CLUSTER_FQDN=$( echo $CLUSTER_ROUTE | awk '{print $2}')
    echo ${CLUSTER_FQDN##*console.}
  register: CLUSTER_NAME


- name:   ðŸš€ INITIALIZATION - Check Cluster Connectivity
  fail: msg="You must be logged in to the server!"
  when: CLUSTER_NAME.stdout==""




- name: ðŸŸ£ Installing {{current_feature.kind}} with the following configuration
  debug:
    var: current_feature
    verbosity: 1





# *************************************************************************************************************************************************
# --------------------------------------------------------------------------------------------------------------------------------------
# Check Encrypted Licenses
# --------------------------------------------------------------------------------------------------------------------------------------
# *************************************************************************************************************************************************
- name: Get Licenses 
  block:
  - name: ðŸ’¾ SET Turbo License from Config File - {{current_feature.turbo_license | default("NONE")}} 
    set_fact: current_turbo_license={{current_feature.turbo_license| default("NONE")}}


- name: Get Licenses from Env Variable
  block:
    - name: ðŸ’¾ SET Turbo License from Env Variable - {{ lookup('ansible.builtin.env', 'TURBO_LICENSE', default='NONE') }}
      set_fact: current_turbo_license={{ lookup('ansible.builtin.env', 'TURBO_LICENSE', default='NONE') }}
  when: current_turbo_license == "NONE" 


- name: Decrypt Licenses 
  block:
  - name: Create Token File
    shell: |
      echo {{global_config.license_token}} > /tmp/pwd.yaml
    ignore_errors: true


  - name: Get License from Vault
    shell: |
      OS=$(uname -s | tr '[:upper:]' '[:lower:]')
      if [ "${OS}" == "darwin" ]; then
            echo "MAC"
            LICENSE_FILE=$(pwd)"/roles/ibm-turbonomic-demo-content/vars/lic.yaml"
      else
            LICENSE_FILE="{{role_path}}/vars/lic.yaml"
      fi    
      echo $LICENSE_FILE
      ansible-vault decrypt --vault-password-file /tmp/pwd.yaml --output /tmp/license.yaml "$LICENSE_FILE"
    ignore_errors: true

  - name: Include License from Vault
    ansible.builtin.include_vars:
      file: /tmp/license.yaml
      name: licenses
    ignore_errors: true

  - name: Cleanup
    shell: |
      rm /tmp/pwd.yaml
      rm /tmp/license.yaml
    ignore_errors: true

  - name: ðŸ’¾ SET Turbo License from Vault
    set_fact: current_turbo_license={{licenses.turbo_license }} 
  when: global_config.license_token is defined 




- name:  ðŸŸ£ Check Turbo License"
  debug:
    msg:
    - "** Missing License Information ***********************************************************************"
    - " Turbo License:      {{ current_turbo_license}}"
    - " âŒ Most of the customization won't work...."
    - ""
  when: current_turbo_license == "NONE"


- name:  ðŸŸ£ Check Sales and Agent Key
  fail: msg="âŒ Missing License Information - Aborting"
  when: current_turbo_license == "NONE"



- name:  ðŸŸ¢ Turbo License - OK"
  debug:
    msg:
    - "** License Information ***********************************************************************"
    - " Turbo License:      {{ current_turbo_license}}"
    - " âœ… OK...."
    - ""
    verbosity: 2
  when: current_turbo_license != "NONE"




# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# INITIALIZATION
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# Placeholder for customization
- name: ðŸ“¥ Init Custom Hook
  include_tasks: 00_init-custom-hook.yaml

# Initialize Logging
- name: ðŸ“¥ Init Logging
  include_tasks: "{{role_path}}/../ibm-install-global/tasks/01_init-logging.yaml"

  
# Start block
- name: ðŸ“¥ Start Logging
  include_tasks: "{{role_path}}/../ibm-install-global/tasks/90-log-start.yaml"




# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# INSTALL TURBONOMIC DEMO CONTENT
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# Install TURBONOMIC
- name: (001/003) - ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡  Install Turbonomic Demo Content
  include_tasks: 10_addons-turbonomic-demo-content.yaml



# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# INSTALL DEMO APPS
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# Create Demo Apps
- name: (002/003) - ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡  Create the Demo Apps 
  include_tasks: 23_addons-demoapps.yaml
  when: current_feature.install_demoapps | default(false) == true


- name: (003/003) - ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡  Create Home UI
  include_tasks: 27_ibm-home-ui.yaml
  when: current_feature.create_home_ui == true | default('false')


# Update IBMAIOps Cards
- name: ðŸ“¥ Update IBMAIOps Cards
  include_tasks: "{{role_path}}/../ibm-install-global/tasks/99_update_cards.yaml"





- name: ðŸ“¥ End Logging
  include_tasks: "{{role_path}}/../ibm-install-global/tasks/91-log-end.yaml"


- name: ðŸ“£ OCP CONSOLE - Create Openshift NOTIFICATION
  shell: |
    oc delete ConsoleNotification --all>/dev/null 2>/dev/null
    export appURL=$(oc get routes -n turbonomic nginx -o jsonpath="{['spec']['host']}")|| true
    cat <<EOF | oc apply -f -
    apiVersion: console.openshift.io/v1
    kind: ConsoleNotification
    metadata:
        name: ibm-aiops-notification-main
    spec:
        backgroundColor: '#009a00'
        color: '#fff'
        link:
            href: "https://$appURL"
            text: Turbonomic
        location: BannerTop
        text: "âœ… IBM Turbonomic is installed in this cluster. ðŸš€ Access it here:"
    EOF

  ignore_errors: true
  args:
    executable: /bin/bash


- name: ðŸŸ£ðŸŸ£ðŸŸ£ðŸŸ£ðŸŸ£ðŸŸ£  âœ… INSTALLATION MODULE DONE - {{current_feature.kind}}
  debug: 
    msg:  

    - "***************************************************************************************************************************************************"
    - "***************************************************************************************************************************************************"
    - "***************************************************************************************************************************************************"
    - "***************************************************************************************************************************************************"
    - "                                                                                                                                                   "
    - "       âœ… IBM IT Automation - DONE INSTALLING {{current_feature.kind}}                                                                                 "
    - "                                                                                                                                                   "
    - "***************************************************************************************************************************************************"
    - "***************************************************************************************************************************************************"
    - "***************************************************************************************************************************************************"
