
# *************************************************************************************************************************************************
# --------------------------------------------------------------------------------------------------------------------------------------
# Patches
# --------------------------------------------------------------------------------------------------------------------------------------
# *************************************************************************************************************************************************


- name: ðŸ©¹ PATCH - Restart Demo UI
  shell: |
    export AIOPS_NAMESPACE=$(oc get po -A|grep aiops-orchestrator-controller |awk '{print$1}')
    if [ "${AIOPS_NAMESPACE}" != "" ]; then
      oc delete pod $(oc get po -n $AIOPS_NAMESPACE-demo-ui|grep demo-ui|awk '{print$1}'):-notfound  --ignore-not-found -n  ibm-aiops-demo-ui --ignore-not-found
    fi
  ignore_errors: true


