

#-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#         ________  __  ___     ___    ________       
#        /  _/ __ )/  |/  /    /   |  /  _/ __ \____  _____
#        / // __  / /|_/ /    / /| |  / // / / / __ \/ ___/
#      _/ // /_/ / /  / /    / ___ |_/ // /_/ / /_/ (__  ) 
#     /___/_____/_/  /_/    /_/  |_/___/\____/ .___/____/  
#                                           /_/
#-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#---------------------------------------------------------------------------------------------------------------------------------------------------"
#  Installing IBM AIOps
#
#  IBM AIOps
#
#  ¬©2023 nikh@ch.ibm.com
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# Installs:
#
#  - ELK
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
 
 
 
- name: ‚ú¥Ô∏è ‚ú¥Ô∏è ‚ú¥Ô∏è INSTALLATION MODULE START - {{current_ibm-aiops_feature.kind}}
  debug: 
    msg: 
    - "***************************************************************************************************************************************************"
    - "***************************************************************************************************************************************************"
    - "***************************************************************************************************************************************************"
    - "***************************************************************************************************************************************************"
    - "                                                                                                                                                   "
    - "      üü°üü°üü°üü°üü°  üöÄ IBM AIOps - INSTALLING {{current_ibm-aiops_feature.kind}} üü°üü°üü°üü°üü°                                                        "
    - "                                                                                                                                                   "
    - "***************************************************************************************************************************************************"
    - "***************************************************************************************************************************************************"
    - "***************************************************************************************************************************************************"



- name: üì£ OCP CONSOLE - Create Openshift NOTIFICATION
  shell: |
    export AIOPS_NAMESPACE=$(oc get po -A|grep aiops-orchestrator-controller |awk '{print$1}')
    appURL=$(oc get routes -n $AIOPS_NAMESPACE-demo-ui $AIOPS_NAMESPACE-demo-ui  -o jsonpath="{['spec']['host']}")|| true
    INSTALL_POD=$(oc get po -n ibm-aiops-installer -l app=ibm-aiops-installer --no-headers|grep "Running"|grep "1/1"|awk '{print$1}')
    
    cat <<EOF | oc apply -f -
    apiVersion: console.openshift.io/v1
    kind: ConsoleNotification
    metadata:
      name: ibm-aiops-notification
    spec:
      backgroundColor: '#141a6b'
      color: '#fff'
      location: {{global_config.position_ocp_notifications | default("BannerTop")}}
      text: 'Installing  {{current_ibm-aiops_feature.kind}} - '  
      link:
          href: "https://$OPENSHIFT_ROUTE/k8s/ns/ibm-aiops-installer/pods/$INSTALL_POD/logs"
          text: Open Logs    
    EOF
  ignore_errors: true


# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# INITIALIZATION
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# Placeholder for customization
- name: üì• Init Custom Hook
  include_tasks: 00_init-custom-hook.yaml

# Initialize Logging
- name: üì• Init Logging
  include_tasks: "{{role_path}}/../ibm-aiops-global/tasks/01_init-logging.yaml"

 
- name: üì• Get Storage Class
  include_tasks: "{{role_path}}/../ibm-aiops-global/tasks/05_init-get-storage-class.yaml"


# Start block
- name: üì• Start Logging
  include_tasks: "{{role_path}}/../ibm-aiops-global/tasks/90-log-start.yaml"



# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# INSTALL ELK
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# Install ELK
- name: üì• Install ELK
  include_tasks: 10_addons-elk.yaml


- name: üì• End Logging
  include_tasks: "{{role_path}}/../ibm-aiops-global/tasks/91-log-end.yaml"


- name: ‚úÖ INSTALLATION MODULE DONE - {{current_ibm-aiops_feature.kind}}
  debug: 
    msg:  

    - "***************************************************************************************************************************************************"
    - "***************************************************************************************************************************************************"
    - "***************************************************************************************************************************************************"
    - "***************************************************************************************************************************************************"
    - "                                                                                                                                                   "
    - "       ‚úÖ IBM AIOps - DONE INSTALLING {{current_ibm-aiops_feature.kind}}                                                                                 "
    - "                                                                                                                                                   "
    - "***************************************************************************************************************************************************"
    - "***************************************************************************************************************************************************"
    - "***************************************************************************************************************************************************"
