---
# *************************************************************************************************************************************************
# --------------------------------------------------------------------------------------------------------------------------------------
# IBMAIOPS INSTANCES
# --------------------------------------------------------------------------------------------------------------------------------------
# *************************************************************************************************************************************************


global_config:
  environment_name: ibm-aiops
  cloud_platform: existing-ocp
  # --------------------------------------------------------------------------------------------------------------------------------------
  # IBMAIOPS Pull Registires
  # --------------------------------------------------------------------------------------------------------------------------------------
  entitled_registry: cp.icr.io
  entitled_registry_user: cp
  catalog_image: icr.io/cpopen/ibm-aiops-catalog:latest
  # Create Welcome Cards in IBMAIOps
  create_cards: true
  # Create App Menu Items in OCP
  create_ocp_items: true
  # Use this Password for all Instances
  # Deployment will not work if these aren't changed
  global_password: CHANGEME
  # Set this value to True to accept all licenses
  accept_all_licenses: False
  # Create Notifications in OCP
  create_ocp_notifications: true
  position_ocp_notifications: BannerTop
  position_final_ocp_notification: BannerTop
  # Key to decrypt Licenses
  # license_token: NONE


openshift:
- name: "mycluster"
  ocp_version: "4.15"
  cluster_name: "mycluster"
  domain_name: example.com
  openshift_storage:
  - storage_name: auto-storage
    storage_type: auto
    # Alternatively use
    #storage_name: ibm-roks-storage
    #storage_type: custom
    #ocp_storage_class_file: ibmc-file-gold-gid
    #ocp_storage_class_block: ibmc-block-gold


ibm-aiops:
- project: ibm-aiops-infra
  instances:
  # --------------------------------------------------------------------------------------------------------------------------------------
  # IBMAIOPS Infrastructure Management
  # --------------------------------------------------------------------------------------------------------------------------------------
  - name: ibm-aiops-infrastructure-management
    kind: InfrastructureManagement
    install: true
    # Version of the catalog subscription
    subscription_channel: v3.7
    # Freeze the version of the Catalog image by patching CatalogSource
    freeze_catalog: false
    
    # LDAP
    install_ldap: true
    # ldap domain
    ldap_domain: ibm.com
    # ldap base
    ldap_base: dc=ibm,dc=com
    # ldap admin password
    #ldap_admin_password: CHANGEME
    # Ldap password for all users
    #ldap_user_password: CHANGEME
    # ldap namespace
    ldap_namespace: openldap

    # --------------------------------------------------------------------------------------------------------------------------------------
    # Storage Classes Override for this Instance (see comment below)
    # --------------------------------------------------------------------------------------------------------------------------------------
    #storage_class_file: automatic
    #storage_class_block: automatic

    # --------------------------------------------------------------------------------------------------------------------------------------
    # Install with CASE Files
    # --------------------------------------------------------------------------------------------------------------------------------------
    case_install: false
    case_github_url: "https://github.com/IBM/cloud-pak/raw/master/repo/case"
    case_name: ibm-cp-aiops
    case_version: 1.5.0
    case_inventory_setup: cpaiopsSetup
    







