

#-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#         ________  __  ___     ___    ________       
#        /  _/ __ )/  |/  /    /   |  /  _/ __ \____  _____
#        / // __  / /|_/ /    / /| |  / // / / / __ \/ ___/
#      _/ // /_/ / /  / /    / ___ |_/ // /_/ / /_/ (__  ) 
#     /___/_____/_/  /_/    /_/  |_/___/\____/ .___/____/  
#                                           /_/
#-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#---------------------------------------------------------------------------------------------------------------------------------------------------"
#  Installing IBM AIOps
#
#  IBM AIOps
#
#  Â©2023 nikh@ch.ibm.com
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# Installs:
#
#  - AIOPS Operator
#  - IBMAIOps
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
 


- name: âœ´ï¸ âœ´ï¸ âœ´ï¸ INSTALLATION MODULE START - {{current_ ibm-aiops_feature.kind}}
  debug: 
    msg: 
    - "***************************************************************************************************************************************************"
    - "***************************************************************************************************************************************************"
    - "***************************************************************************************************************************************************"
    - "***************************************************************************************************************************************************"
    - "                                                                                                                                                   "
    - "      ï¿½ IBM AIOps - INSTALLING {{current_ ibm-aiops_feature.kind}} "
    - "                                                                                                                                                   "
    - "***************************************************************************************************************************************************"
    - "***************************************************************************************************************************************************"
    - "***************************************************************************************************************************************************"


- name: Log
  shell: |
    export MESSAGE="Installing Demo Apps"
    export currentDate=$(date +%Y-%m-%d_%H:%M)
    echo "---------------------------------------------------------------------------------------------------------------------------------------------------" >> ../install_{{current_ ibm-aiops_feature.kind}}.log
    echo $currentDate" - "$MESSAGE  >> ../install_{{current_ ibm-aiops_feature.kind}}.log
  ignore_errors: true



- name: ðŸ“£ OCP CONSOLE - Create Openshift NOTIFICATION
  shell: |
    export AIOPS_NAMESPACE=$(oc get po -A|grep aiops-orchestrator-controller |awk '{print$1}')
    appURL=$(oc get routes -n $AIOPS_NAMESPACE-demo-ui $AIOPS_NAMESPACE-demo-ui  -o jsonpath="{['spec']['host']}")|| true

    cat <<EOF | oc apply -f -
    apiVersion: console.openshift.io/v1
    kind: ConsoleNotification
    metadata:
      name:  ibm-aiops-notification
    spec:
      backgroundColor: '#141a6b'
      color: '#fff'
      location: {{global_config.position_ocp_notifications | default("BannerTop")}}
      text: 'Installing  {{current_ ibm-aiops_feature.kind}}'    
    EOF
  ignore_errors: true



- name:  ðŸŸ¡ðŸŸ¡ðŸŸ¡ INITIALIZATION - Installation Parameters ðŸŸ¡ðŸŸ¡ðŸŸ¡"
  debug:
    msg:
    - "***********************************************************************************************"
    - " ðŸš€ Installing {{current_ ibm-aiops_feature.kind}}"
    - "***********************************************************************************************"
    - "-----------------------------------------------------------------------------------------------"
    - "  ðŸ“¥ STORAGE"
    - "     ðŸ’¾ Installation Options for SPECIFIC MODULE {{ current_ ibm-aiops_feature.kind}}"
    - "        Storage Class File Override:             {{ current_ ibm-aiops_feature.storage_class_file | default('no override') }}"
    - "        Storage Class Block Override:            {{ current_ ibm-aiops_feature.storage_class_block | default('no override') }}"
    - "        Storage Class InfraManagement:           {{ current_ ibm-aiops_feature.storage_class_file | default('no override') }}"
    - ""
    - "     ðŸ’¾ Installation Options from GLOBAL"
    - "        Storage Class File Override:             {{ ocp_storage_class_file | default('not defined') }}"
    - "        Storage Class Block Override:            {{ ocp_storage_class_block | default('not defined') }}"
    - "        Storage Class InfraManagement:           {{ ocp_storage_class_file | default('not defined') }}"
    - "-----------------------------------------------------------------------------------------------"
    - "  ðŸ“¥ CONFIG"
    - "     âœ… Installation Name:                        {{current_ ibm-aiops_feature.aiops_name}}"
    - "     ðŸ”Ž IBMAIOps Size:                           {{current_ ibm-aiops_feature.aiops_size}}"
    - "     ðŸ”½ Custom Sizing File:                       {{current_ ibm-aiops_feature.custom_size_file | default('none')}}"
    - "     ðŸ”½ Install Feature Flags:                    {{current_ ibm-aiops_feature.install_feature_flags | default('not defined')}}"
    - "-----------------------------------------------------------------------------------------------"
    - "  ðŸ“¥ VERSION "
    - "     ðŸš€ Subscription Channel:                     {{current_ ibm-aiops_feature.subscription_channel}}"
    - "     ðŸ”½ Freeze the Catalog Image Version:         {{current_ ibm-aiops_feature.freeze_catalog  | default('not defined')}}"
    - "     âœ… Install with CASE:                        {{current_ ibm-aiops_feature.case_install}}"
    - "-----------------------------------------------------------------------------------------------"
    - "***********************************************************************************************"

- name: ðŸŸ£ Installing {{current_ ibm-aiops_feature.kind}} with the following configuration
  debug:
    var: current_ ibm-aiops_feature



# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# INITIALIZATION
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# Placeholder for customization
- name: ðŸŸ¡ðŸŸ¡ðŸŸ¡ Initialize Custom Hook
  include_tasks: 00_init-custom-hook.yaml

# Initialize Logging
- name: ðŸŸ¡ðŸŸ¡ðŸŸ¡ Initialize Logging
  include_tasks: "{{role_path}}/../ ibm-aiops-global/tasks/01_init-logging.yaml"
    
- name: ðŸŸ¡ðŸŸ¡ðŸŸ¡ Initialization Checks
  include_tasks: 02_init_checks.yaml
# Start block
- name: ðŸŸ¡ðŸŸ¡ðŸŸ¡ Start Logging
  include_tasks: "{{role_path}}/../ ibm-aiops-global/tasks/90-log-start.yaml"

# Run Prerequisites
- name: ðŸŸ¡ðŸŸ¡ðŸŸ¡ Initialization of the Installation
  include_tasks: 03_init-initialization.yaml
  




# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# TEST
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# - name: ðŸŸ¡ðŸŸ¡ðŸŸ¡  Create Routes
#   include_tasks: 30_ ibm-aiops-create-routes.yaml

# # Update IBMAIOps Cards
# - name: ðŸŸ¡ðŸŸ¡ðŸŸ¡ Update IBMAIOps Cards
#   include_tasks: "{{role_path}}/../ ibm-aiops-global/tasks/99_update_cards.yaml"

# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# TEST
# ---------------------------------------------------------------------------------------------------------------------------------------------------"




- name: ðŸŸ¡ðŸŸ¡ðŸŸ¡ Get Storage Classes
  include_tasks: "{{role_path}}/../ ibm-aiops-global/tasks/05_init-get-storage-class.yaml"


- name: ðŸŸ¡ðŸŸ¡ðŸŸ¡ Install IBMAIOps Prerequisites 
  include_tasks: 06_ ibm-aiops-prerequisites.yaml
      

# Install IBMAIOPS Operator
- name: ðŸŸ¡ðŸŸ¡ðŸŸ¡ IBMAIOps Custom Hook
  include_tasks: 08_ ibm-aiops-custom-hook.yaml



# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# INSTALL CATALOG with YAML FILE
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
- name: ðŸŸ¡ðŸŸ¡ðŸŸ¡ Install IBMAIOps Catalog - Classic Way (skipped if CASE selected)
  include_tasks: 10_ ibm-aiops-catalog.yaml
  when: current_ ibm-aiops_feature.case_install==false


# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# INSTALL CATALOG with CASE FILE
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
- name: ðŸŸ¡ðŸŸ¡ðŸŸ¡ Install IBMAIOps Catalog - Save Case File (this can take some time - skipped if not selected)
  include_role:
    name:  ibm-aiops-case-save
  when: current_ ibm-aiops_feature.case_install==true


- name: ðŸŸ¡ðŸŸ¡ðŸŸ¡ Install IBMAIOps Catalog - Create CatalogSources from Case File (this can take some time - skipped if not selected)
  include_role:
    name:  ibm-aiops-case-catalog-source
  when: current_ ibm-aiops_feature.case_install==true



# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# INSTALL IBMAIOPS OPERATOR
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
- name: ðŸŸ¡ðŸŸ¡ðŸŸ¡ Install the IBMAIOps Operator
  include_tasks: 11_ ibm-aiops-operator.yaml


# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# INSTALL FEATURE FLAGS
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# Install  Feature Flags
- name: ðŸŸ¡ðŸŸ¡ðŸŸ¡  Install IBMAIOPS Feature Flags
  include_tasks: 12_ ibm-aiops-featureflags.yaml
  when: current_ ibm-aiops_feature.install_feature_flags == true | default('false')



# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# INSTALL IBMAIOPS
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# Install IBMAIOPS Instance
- name: ðŸŸ¡ðŸŸ¡ðŸŸ¡ Install the IBMAIOps Instance
  include_tasks: 19_ ibm-aiops-install.yaml
      




# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# WAIT FOR INSTALLATION READY
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# Wait for Common Services being completely installed
- name: ðŸŸ¡ðŸŸ¡ðŸŸ¡ Wait for CommonServices to be ready
  include_tasks: 99_ ibm-aiops-wait-common-services.yaml
- name: ðŸŸ¡ðŸŸ¡ðŸŸ¡ Wait for Zen Initialisation
  include_tasks: 99_ ibm-aiops-wait-for-zen.yaml
      

# Patching Topology Deployment
- name: ðŸŸ¡ðŸŸ¡ðŸŸ¡ Patch IBMAIOPS Topology
  include_tasks: 20_ ibm-aiops-patch-topology.yaml


# Wait for IBMAIOPS being completely installed
- name: ðŸŸ¡ðŸŸ¡ðŸŸ¡ Wait for IBMAIOps to be ready
  include_tasks: 99_ ibm-aiops-wait- ibm-aiops.yaml

# --------------------------------------------------------------------------------------------------------------------------------------
# Create Openshift WebConsole Menu Item
# --------------------------------------------------------------------------------------------------------------------------------------
- name: ðŸŸ¡ðŸŸ¡ðŸŸ¡  Create IBMAIOps Openshift WebConsole Menu Item
  include_tasks: 91_ ibm-aiops-create-ocp-menu.yaml
  when: global_config.create_ocp_items | default(true) == true  

# Update IBMAIOps Cards
- name: ðŸŸ¡ðŸŸ¡ðŸŸ¡ Update IBMAIOps Cards
  include_tasks: "{{role_path}}/../ ibm-aiops-global/tasks/99_update_cards.yaml"

  
# Access and documentaiton
- name: ðŸŸ¡ðŸŸ¡ðŸŸ¡ Get all logins
  include_tasks: "{{role_path}}/../ ibm-aiops-global/tasks/90_core-get-all-logins.yaml"



- name: ðŸŸ¡ðŸŸ¡ðŸŸ¡ Open IBMAIOps
  include_tasks: "{{role_path}}/../ ibm-aiops-global/tasks/99_open-aimanager.yaml"


- name: ðŸŸ¡ðŸŸ¡ðŸŸ¡ Open Documentation
  include_tasks: "{{role_path}}/../ ibm-aiops-global/tasks/99_open-doc.yaml"



- name: ðŸŸ¡ðŸŸ¡ðŸŸ¡ End Logging
  include_tasks: "{{role_path}}/../ ibm-aiops-global/tasks/91-log-end.yaml"




- name: âœ… INSTALLATION MODULE DONE - {{current_ ibm-aiops_feature.kind}}
  debug: 
    msg: 
    - "***************************************************************************************************************************************************"
    - "***************************************************************************************************************************************************"
    - "***************************************************************************************************************************************************"
    - "***************************************************************************************************************************************************"
    - "                                                                                                                                                   "
    - "       âœ… IBM AIOps - DONE INSTALLING {{current_ ibm-aiops_feature.kind}}                                                                                 "
    - "                                                                                                                                                   "
    - "***************************************************************************************************************************************************"
    - "***************************************************************************************************************************************************"
    - "***************************************************************************************************************************************************"
