

# *************************************************************************************************************************************************
# --------------------------------------------------------------------------------------------------------------------------------------
# Patching some stuff
# --------------------------------------------------------------------------------------------------------------------------------------
# *************************************************************************************************************************************************
    

- name: ðŸ›°ï¸  START - OCP MENU
  debug: 
    msg="{{ lookup('pipe','date +%d.%m.%Y---%H:%M:%S') }}"


- name: Log
  shell: |
    export MESSAGE="Create Openshift WebConsole Menu Item"
    export currentDate=$(date +%Y-%m-%d_%H:%M)
    echo "---------------------------------------------------------------------------------------------------------------------------------------------------" >> ../install_{{current_ibmaiops_cluster.kind}}.log
    echo $currentDate" - "$MESSAGE  >> ../install_{{current_ibmaiops_cluster.kind}}.log
  ignore_errors: true

- name: ðŸ“£ OCP CONSOLE - Create Openshift NOTIFICATION
  shell: |
    cat <<EOF | oc apply -f -
    apiVersion: console.openshift.io/v1
    kind: ConsoleNotification
    metadata:
      name: ibm-aiops-notification
    spec:
      backgroundColor: '#ffd500'
      color: '#000'
      location: {{global_config.position_ocp_notifications | default("BannerTop")}}
      text: 'Installing {{current_ibmaiops_cluster.kind}} - Create Openshift WebConsole Menu Item'    
    EOF
  ignore_errors: true
  when: global_config.create_ocp_notifications | default(true) == true  
   


- name: ðŸŒ OCP MENU - Create Openshift WebConsole Menu Item
  shell: |
    export AIOPS_NAMESPACE=$(oc get po -A|grep aiops-orchestrator-controller |awk '{print$1}')
    appURL=$(oc get route -n $AIOPS_NAMESPACE cpd -o jsonpath={.spec.host})|| true

    cat <<EOF | oc apply -f -
      apiVersion: console.openshift.io/v1
      kind: ConsoleLink
      metadata:
        name: ibm-aiops-aimanager
      spec:
        applicationMenu:
          imageURL: >-
            https://raw.githubusercontent.com/niklaushirt/ ibm-aiops-deployer/main/doc/pics/icons/ ibm-aiops6.svg
          section: IBM Cloud Paks
        href: >-
          https://$appURL
        location: ApplicationMenu
        text: IBM AIOps
    EOF
  ignore_errors: true



