
# *************************************************************************************************************************************************
# --------------------------------------------------------------------------------------------------------------------------------------
# Waiting for IBM AIOPS installation to finish
# --------------------------------------------------------------------------------------------------------------------------------------
# *************************************************************************************************************************************************
    


- name: Log
  shell: |
    export MESSAGE=" ðŸ•¦ Wait for IBM AIOps to become ready"
    export currentDate=$(date +%Y-%m-%d_%H:%M)
    echo "---------------------------------------------------------------------------------------------------------------------------------------------------" >> ../install_{{current_ibm-aiops_feature.kind}}.log
    echo $currentDate" - "$MESSAGE  >> ../install_{{current_ibm-aiops_feature.kind}}.log
  ignore_errors: true

- name: ðŸ“£ OCP CONSOLE - Create Openshift NOTIFICATION
  shell: |
    cat <<EOF | oc apply -f -
    apiVersion: console.openshift.io/v1
    kind: ConsoleNotification
    metadata:
      name: ibm-aiops-notification
    spec:
      backgroundColor: '#ff7700'
      color: '#000'
      location: {{global_config.position_ocp_notifications | default("BannerTop")}}
      text: 'Installing {{current_ibm-aiops_feature.kind}} - ðŸ•¦ Wait for IBM AIOps to become ready (about 10-20 minutes) - Started at $(date +%H:%M:%S) UTC'    
    EOF
  ignore_errors: true
  when: global_config.create_ocp_notifications | default(true) == true  


# --------------------------------------------------------------------------------------------------------------------------------------
# Wait for {{ current_ibm-aiops_cluster.project }} Namespace to be ready
# --------------------------------------------------------------------------------------------------------------------------------------

- name: ðŸ•¦ CHECK -  Wait for more than >{{ aiops_ns_min_pods_final }} pods in namespace {{ current_ibm-aiops_cluster.project }} (this might take some time)
  shell: |
    NUM_PODS=$(oc get po -n {{ current_ibm-aiops_cluster.project }} |grep Running| wc -l)
    echo $NUM_PODS
  register: kubectl_num_pods
  until: kubectl_num_pods.stdout|int > aiops_ns_min_pods_final
  retries: 500
  delay: 15




- name: ðŸ•¦ CHECK -  Wait for {{ current_ibm-aiops_cluster.project }} to become ready (this might take some time)
  shell: oc get po -n {{ current_ibm-aiops_cluster.project }} | grep -v Running |grep -v Completed|grep -v Error |grep -v zen-tour-job| wc -l| tr -d ' '
  register: kubectl_get_pods
  until: kubectl_get_pods.stdout|int == 1
  retries: 500
  delay: 15


- name: ðŸ•¦ CHECK -  Wait for all Pods in {{ current_ibm-aiops_cluster.project }} to become ready (this might take some time)
  shell: oc get po -n {{ current_ibm-aiops_cluster.project }} | grep -v Completed | grep -v Error |grep "0/" |wc -l| tr -d ' '
  register: kubectl_get_pods
  until: kubectl_get_pods.stdout == "0"
  retries: 500
  delay: 15


- name: Log
  shell: |
    export MESSAGE=" âœ… IBM AIOps is ready"
    export currentDate=$(date +%Y-%m-%d_%H:%M)
    echo $currentDate" - "$MESSAGE  >> ../install_{{current_ibm-aiops_feature.kind}}.log
  ignore_errors: true

- name: ðŸ“£ OCP CONSOLE - Create Openshift NOTIFICATION
  shell: |
    cat <<EOF | oc apply -f -
    apiVersion: console.openshift.io/v1
    kind: ConsoleNotification
    metadata:
      name: ibm-aiops-notification
    spec:
      backgroundColor: '#009a00'
      color: '#000'
      location: {{global_config.position_ocp_notifications | default("BannerTop")}}
      text: 'Installing {{current_ibm-aiops_feature.kind}} - IBM AIOps is ready'    
    EOF
  ignore_errors: true
  when: global_config.create_ocp_notifications | default(true) == true  

