
# *************************************************************************************************************************************************
# --------------------------------------------------------------------------------------------------------------------------------------
# Waiting for CP4AIOPS Event Manager installation to finish
# --------------------------------------------------------------------------------------------------------------------------------------
# *************************************************************************************************************************************************
    


- name: Log
  shell: |
    export MESSAGE=" üï¶ Wait for Event Manager to become ready"
    export currentDate=$(date +%Y-%m-%d_%H:%M)
    echo "---------------------------------------------------------------------------------------------------------------------------------------------------" >> ../install_{{current_feature.kind}}.log
    echo $currentDate" - "$MESSAGE  >> ../install_{{current_feature.kind}}.log
  ignore_errors: true


# --------------------------------------------------------------------------------------------------------------------------------------
# Wait for EventManager Namespace to be ready
# --------------------------------------------------------------------------------------------------------------------------------------

- name: üï¶ CHECK -  Wait for more than >{{evtmgr_ns_min_pods_final}} pods in namespace {{current_ibm_feature.project}}
  shell: |
    NUM_PODS=$(oc get po -n {{current_ibm_feature.project}} |grep Running| wc -l)
    echo $NUM_PODS
  register: kubectl_num_pods
  until: kubectl_num_pods.stdout|int > {{evtmgr_ns_min_pods_final}}
  retries: 500
  delay: 15


- name: üï¶ CHECK -  Wait for WEBGUI to become ready
  shell: |
    WEBGUI_PODS=$(oc get po -n {{current_ibm_feature.project}} | grep evtmanager-webgui-0)
    echo $WEBGUI_PODS
  register: kubectl_webgui_pods
  until: ("2/2" in kubectl_webgui_pods.stdout)
  retries: 500
  delay: 15


# - name: üï¶ CHECK -  Wait for all Pods in {{ current_ibm_feature.project }} to become ready (this might take some time)
#   shell: oc get po -n {{ current_ibm_feature.project }} | grep -v Completed | grep -v Error |grep "0/" |wc -l| tr -d ' '
#   register: kubectl_get_pods
#   until: kubectl_get_pods.stdout == "0"
#   retries: 500
#   delay: 15


# --------------------------------------------------------------------------------------------------------------------------------------
# AIOPS
# --------------------------------------------------------------------------------------------------------------------------------------
- name: üöÄ LOGIN - AIOPS Event Manager (NOI)
  shell: |
    echo "***************************************************************************************************************************************************"
    echo "***************************************************************************************************************************************************"
    echo "üöÄ Event Manager (Netcool Operations Insight) Connection Details"
    echo "***************************************************************************************************************************************************"
    echo "***************************************************************************************************************************************************"

    echo "---------------------------------------------------------------------------------------------"
    echo "    SMADMIN USER:"
    echo "        User:     smadmin"   
    echo "        Password: $(oc get secret -n {{current_ibm_feature.project}} evtmanager-was-secret -o jsonpath='{.data.WAS_PASSWORD}'| base64 --decode && echo)"


    echo "---------------------------------------------------------------------------------------------"
    echo "---------------------------------------------------------------------------------------------"

    echo "    EventManager (NOI):"
    echo "        URL:     https://netcool-evtmanager.{{CLUSTER_NAME.stdout_lines[0]}}/"
  register: output_string
  ignore_errors: true
- name: üîê LOGIN - AIOPS Event Manager (NOI)
  debug: 
    var: output_string.stdout_lines
  #when: PRINT_LOGINS == true


