

# *************************************************************************************************************************************************
# --------------------------------------------------------------------------------------------------------------------------------------
# Patching some stuff
# --------------------------------------------------------------------------------------------------------------------------------------
# *************************************************************************************************************************************************
    

- name: ðŸ›°ï¸  START - OCP MENU
  debug: 
    msg="{{ lookup('pipe','date +%d.%m.%Y---%H:%M:%S') }}"


- name: Log
  shell: |
    export MESSAGE="Create Openshift WebConsole Menu Item"
    export currentDate=$(date +%Y-%m-%d_%H:%M)
    echo "---------------------------------------------------------------------------------------------------------------------------------------------------" >> ../install_{{current_feature.kind}}.log
    echo $currentDate" - "$MESSAGE  >> ../install_{{current_feature.kind}}.log
  ignore_errors: true

- name: ðŸ“£ OCP CONSOLE - Create Openshift NOTIFICATION
  shell: |
    cat <<EOF | oc apply -f -
    apiVersion: console.openshift.io/v1
    kind: ConsoleNotification
    metadata:
      name: ibm-aiops-notification
    spec:
      backgroundColor: '#ffd500'
      color: '#000'
      location: {{global_config.position_ocp_notifications | default("BannerTop")}}
      text: 'Installing {{current_feature.kind}} - Create Openshift WebConsole Menu Item'    
    EOF
  ignore_errors: true
  args:
    executable: /bin/bash
  when: global_config.create_ocp_notifications | default(true) == true  
   




- name: ðŸŒ OCP MENU - Create Openshift WebConsole Menu Item - Turbonomic
  shell: |
    appURL=$(oc get route -n turbonomic nginx -o jsonpath={.spec.host})|| true

    cat <<EOF | oc apply -f -
      apiVersion: console.openshift.io/v1
      kind: ConsoleLink
      metadata:
        name: ibm-turbonomic-install
      spec:
        applicationMenu:
          imageURL: >-
            https://raw.githubusercontent.com/niklaushirt/ibm-aiops-deployer/main/doc/pics/icons/turbo-icon.svg
          section: IBM IT Automation
        href: >-
          https://$appURL
        location: ApplicationMenu
        text: Turbonomic
    EOF
  ignore_errors: true
  args:
    executable: /bin/bash

