
# *************************************************************************************************************************************************
# --------------------------------------------------------------------------------------------------------------------------------------
# Install Turbonomic
# --------------------------------------------------------------------------------------------------------------------------------------
# *************************************************************************************************************************************************

# --------------------------------------------------------------------------------------------------------------------------------------
# Install Turbonomic
# --------------------------------------------------------------------------------------------------------------------------------------

- name: ðŸ›°ï¸  START - INSTALL INSTANA AGENT
  debug: 
    msg="{{ lookup('pipe','date +%d.%m.%Y---%H:%M:%S') }}"


- name: Log
  shell: |
    export MESSAGE="Installing INSTANA AGENT"
    export currentDate=$(date +%Y-%m-%d_%H:%M)
    echo "---------------------------------------------------------------------------------------------------------------------------------------------------" >> ../install_{{current_ibmaiops_feature.kind}}.log
    echo $currentDate" - "$MESSAGE  >> ../install_{{current_ibmaiops_feature.kind}}.log
  ignore_errors: true

- name: ðŸ“£ OCP CONSOLE - Create Openshift NOTIFICATION
  shell: |
    cat <<EOF | oc apply -f -
    apiVersion: console.openshift.io/v1
    kind: ConsoleNotification
    metadata:
      name: ibm-aiops-notification
    spec:
      backgroundColor: '#ffd500'
      color: '#000'
      location: {{global_config.position_ocp_notifications | default("BannerTop")}}
      text: 'Installing {{current_ibmaiops_feature.kind}} - Instana Agent'    
    EOF
  ignore_errors: true
  args:
    executable: /bin/bash
  when: global_config.create_ocp_notifications | default(true) == true  




- name: ðŸš€ INSTANA AGENT - Get BASE_DOMAIN
  shell: |
    CLUSTER_ROUTE=$(oc get routes console -n openshift-console | tail -n 1 2>&1 ) 
    CLUSTER_FQDN=$( echo $CLUSTER_ROUTE | awk '{print $2}')
    CLUSTER_NAME=${CLUSTER_FQDN##*console.}


    #BASE_DOMAIN="dev-aiops-instana-core.$CLUSTER_NAME"
    BASE_DOMAIN="$CLUSTER_NAME"
    echo $BASE_DOMAIN
    
  ignore_errors: true
  register: output
        
- name: ðŸš€ INSTANA AGENT - Set BASE_DOMAIN - {{ output.stdout_lines }} 
  set_fact: BASE_DOMAIN={{ output.stdout_lines[0] }} 





- name: ðŸš€ INSTANA AGENT - Create Namespace
  shell: |
    oc create ns instana-agent
    oc adm policy add-scc-to-user privileged -z instana-agent
  ignore_errors: true
  register: output
  args:
    executable: /bin/bash
- name: ðŸŸ£  OUTPUT
  debug:
    var: output.stdout_lines
    verbosity: 1



- name: ðŸš€ INSTANA AGENT - Create Download Keys Secret
  shell: |
    oc create secret generic instana-agent -n instana-agent --from-literal=downloadKey={{current_agent_key}}  --from-literal=key={{current_agent_key}}
  ignore_errors: true
  register: output
  args:
    executable: /bin/bash
- name: ðŸŸ£  OUTPUT
  debug:
    var: output.stdout_lines
    verbosity: 1


- name: ðŸš€ INSTANA AGENT - Create Operator
  shell: |
    kubectl apply -f https://github.com/instana/instana-agent-operator/releases/latest/download/instana-agent-operator.yaml  
  ignore_errors: true
  register: output
  args:
    executable: /bin/bash
- name: ðŸŸ£  OUTPUT
  debug:
    var: output.stdout_lines
    verbosity: 1



- name:   ðŸ•¦ INSTANA - Wait for Operator to become ready
  shell: |
    while [ `oc -n instana-agent get pods| grep '1/1' | grep -c ""` -lt 2 ]
    do
      sleep 10
    done
  ignore_errors: true
  register: output
  args:
    executable: /bin/bash
- name: ðŸŸ£  OUTPUT
  debug:
    var: output.stdout_lines
    verbosity: 1



- name: ðŸš€ INSTANA AGENT - Create Agent
  kubernetes.core.k8s:
    namespace: instana-agent
    state: present
    template: ./templates/instana-agent/instana-agent-cr.j2


