

# *************************************************************************************************************************************************
# --------------------------------------------------------------------------------------------------------------------------------------
# Wait for Zen in Common Services being ready
# --------------------------------------------------------------------------------------------------------------------------------------
# *************************************************************************************************************************************************



- name: Log
  shell: |
    export MESSAGE=" ðŸŸ£ðŸŸ£ðŸŸ£ Starting {{current_ibmaiops_cluster.kind}} Install - {{role_name}}"
    export currentDate=$(date +%Y-%m-%d_%H:%M)
    echo "**********************************************************************************************************************************************************" >> ../install_{{current_ibmaiops_cluster.kind}}.log
    echo "**********************************************************************************************************************************************************" >> ../install_{{current_ibmaiops_cluster.kind}}.log
    echo $currentDate" - "$MESSAGE  >> ../install_{{current_ibmaiops_cluster.kind}}.log



  ignore_errors: true


