

# *************************************************************************************************************************************************
# --------------------------------------------------------------------------------------------------------------------------------------
# Wait for Common Services being ready
# --------------------------------------------------------------------------------------------------------------------------------------
# *************************************************************************************************************************************************


- name: Log
  shell: |
    export MESSAGE=" ðŸ•¦ Wait for Common Services to become ready"
    export currentDate=$(date +%Y-%m-%d_%H:%M)
    echo "---------------------------------------------------------------------------------------------------------------------------------------------------" >> ../install_{{current_ibmaiops_cluster.kind}}.log
    echo $currentDate" - "$MESSAGE  >> ../install_{{current_ibmaiops_cluster.kind}}.log
  ignore_errors: true

- name: ðŸ“£ OCP CONSOLE - Create Openshift NOTIFICATION
  shell: |
    cat <<EOF | oc apply -f -
    apiVersion: console.openshift.io/v1
    kind: ConsoleNotification
    metadata:
      name: ibm-aiops-notification
    spec:
      backgroundColor: '#ff7700'
      color: '#000'
      location: {{global_config.position_ocp_notifications | default("BannerTop")}}
      text: 'Installing {{current_ibmaiops_cluster.kind}} - ðŸ•¦ Wait for Common Services to become ready (about 15-20 minutes) - Started at $(date +%H:%M:%S) UTC'    
    EOF
  ignore_errors: true
  when: global_config.create_ocp_notifications | default(true) == true  


# --------------------------------------------------------------------------------------------------------------------------------------
# Wait for Common Services
# --------------------------------------------------------------------------------------------------------------------------------------

- name: ðŸ•¦ CHECK -  Wait for more than >{{ cs_ns_min_pods }} pods in namespace ibm-common-services (this might take some time)
  shell: |
    NUM_PODS=$(oc get po -n ibm-common-services |grep Running| wc -l)
    echo $NUM_PODS
  register: kubectl_num_pods
  until: kubectl_num_pods.stdout|int > cs_ns_min_pods
  retries: 150
  delay: 15




- name: ðŸ•¦ CHECK -  Wait for ibm-common-services to become ready (this might take some time)
  shell: oc get po -n ibm-common-services | grep -v Running |grep -v Completed | grep -c ""
  register: kubectl_get_pods
  until: kubectl_get_pods.stdout == "1"
  retries: 150
  delay: 15



- name: Log
  shell: |
    export MESSAGE=" âœ… Common Services is ready"
    export currentDate=$(date +%Y-%m-%d_%H:%M)
    echo $currentDate" - "$MESSAGE  >> ../install_{{current_ibmaiops_cluster.kind}}.log
  ignore_errors: true

- name: ðŸ“£ OCP CONSOLE - Create Openshift NOTIFICATION
  shell: |
    cat <<EOF | oc apply -f -
    apiVersion: console.openshift.io/v1
    kind: ConsoleNotification
    metadata:
      name: ibm-aiops-notification
    spec:
      backgroundColor: '#009a00'
      color: '#000'
      location: {{global_config.position_ocp_notifications | default("BannerTop")}}
      text: 'Installing {{current_ibmaiops_cluster.kind}} - Common Services is ready'    
    EOF
  ignore_errors: true
  when: global_config.create_ocp_notifications | default(true) == true  
