

#-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#         ________  __  ___     ___    ________       
#        /  _/ __ )/  |/  /    /   |  /  _/ __ \____  _____
#        / // __  / /|_/ /    / /| |  / // / / / __ \/ ___/
#      _/ // /_/ / /  / /    / ___ |_/ // /_/ / /_/ (__  ) 
#     /___/_____/_/  /_/    /_/  |_/___/\____/ .___/____/  
#                                           /_/
#-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#---------------------------------------------------------------------------------------------------------------------------------------------------"
#  Installing IBM Concert
#
#  IBM Concert
#
#  Â©2024 nikh@ch.ibm.com
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# Installs:
#
#  - IBM Concert
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
 


- name: ðŸŸ£ðŸŸ£ðŸŸ£ðŸŸ£ðŸŸ£ðŸŸ£  INSTALLATION MODULE START - {{current_ibmaiops_feature.kind}}
  debug: 
    msg: 
    - "***************************************************************************************************************************************************"
    - "***************************************************************************************************************************************************"
    - "***************************************************************************************************************************************************"
    - "***************************************************************************************************************************************************"
    - "                                                                                                                                                   "
    - "      ï¿½ IBM AIOps - INSTALLING {{current_ibmaiops_feature.kind}} "
    - "                                                                                                                                                   "
    - "***************************************************************************************************************************************************"
    - "***************************************************************************************************************************************************"
    - "***************************************************************************************************************************************************"


- name: Log
  shell: |
    export MESSAGE="Installing IBM AIOps"
    export currentDate=$(date +%Y-%m-%d_%H:%M)
    echo "---------------------------------------------------------------------------------------------------------------------------------------------------" >> ../install_{{current_ibmaiops_feature.kind}}.log
    echo $currentDate" - "$MESSAGE  >> ../install_{{current_ibmaiops_feature.kind}}.log
  ignore_errors: true



- name: ðŸ“£ OCP CONSOLE - Create Openshift NOTIFICATION
  shell: |
    OPENSHIFT_ROUTE=$(oc get route -n openshift-console console -o jsonpath={.spec.host})
    INSTALL_POD=$(oc get po -n ibm-concert-installer -l app=ibm-aiops-concert --no-headers|grep "Running"|grep "1/1"|awk '{print$1}')

    cat <<EOF | oc apply -f -
    apiVersion: console.openshift.io/v1
    kind: ConsoleNotification
    metadata:
      name: ibm-aiops-notification-main
    spec:
      backgroundColor: '#141a6b'
      color: '#fff'
      location: {{global_config.position_final_ocp_notification | default("BannerTop")}}
      text: 'Installing  {{current_ibmaiops_feature.kind}} ' 
      link:
          href: "https://$OPENSHIFT_ROUTE/k8s/ns/ibm-concert-installer/pods/$INSTALL_POD/logs"
          text: Open Logs   
    EOF
  ignore_errors: true
  args:
    executable: /bin/bash



- name:  ðŸŸ¡ðŸŸ¡ðŸŸ¡ INITIALIZATION - Installation Parameters ðŸŸ¡ðŸŸ¡ðŸŸ¡"
  debug:
    msg:
    - "***********************************************************************************************"
    - " ðŸš€ Installing {{current_ibmaiops_feature.kind}}"
    - "***********************************************************************************************"
    - "-----------------------------------------------------------------------------------------------"
    - "  ðŸ“¥ STORAGE"
    - "     ðŸ’¾ Installation Options for SPECIFIC MODULE {{ current_ibmaiops_feature.kind}}"
    - "        Storage Class File Override:             {{ current_ibmaiops_feature.storage_class_file | default('no override') }}"
    - "        Storage Class Block Override:            {{ current_ibmaiops_feature.storage_class_block | default('no override') }}"
    - ""
    - "     ðŸ’¾ Installation Options from GLOBAL"
    - "        Storage Class File Override:             {{ ocp_storage_class_file | default('not defined') }}"
    - "        Storage Class Block Override:            {{ ocp_storage_class_block | default('not defined') }}"
    - "-----------------------------------------------------------------------------------------------"
    - "  ðŸ“¥ CONFIG"
    - "     âœ… IBM Concert Project Instance Name:        {{current_ibmaiops_feature.project_instance| default('not defined')}}"
    - "     ðŸ”Ž IBM Concert Namespace:                    {{current_ibmaiops_feature.project| default('not defined')}}"
    - "     ðŸ“£ IBM Concert prod_registry:                {{current_ibmaiops_feature.prod_registry| default('not defined')}}"
    - "     ðŸ“£ IBM Concert prod_user:                    {{current_ibmaiops_feature.prod_user| default('not defined')}}"
    - "     ðŸ“£ IBM Concert private_registry_location:    {{current_ibmaiops_feature.private_registry_location| default('not defined')}}"
    - "     ðŸ“£ IBM Concert project_operator:             {{current_ibmaiops_feature.project_operator| default('not defined')}}"
    - "     ðŸ“£ IBM Concert docker_exe:                   {{current_ibmaiops_feature.docker_exe| default('not defined')}}"
    - "-----------------------------------------------------------------------------------------------"
    - "***********************************************************************************************"




- name: ðŸŸ£ Installing {{current_ibmaiops_feature.kind}} with the following configuration
  debug:
    var: current_ibmaiops_feature

# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# INITIALIZATION
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# Placeholder for customization
- name: (001/019) - ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡ Initialize Custom Hook
  include_tasks: 00_init-custom-hook.yaml

# Initialize Logging
- name: (002/019) - ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡ Initialize Logging
  include_tasks: "{{role_path}}/../ibm-aiops-global/tasks/01_init-logging.yaml"
    
- name: (003/019) - ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡ Initialization Checks
  include_tasks: 02_init-checks.yaml
 
- name: (004/019) - ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡ Start Logging
  include_tasks: "{{role_path}}/../ibm-aiops-global/tasks/90-log-start.yaml"

# Run Prerequisites
- name: (005/019) - ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡ Initialization of the Installation
  include_tasks: 03_init-initialization.yaml


- name: (006/019) - ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡ Get Storage Classes
  include_tasks: "{{role_path}}/../ibm-aiops-global/tasks/05_init-get-storage-class.yaml"




# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# INSTALL PREREQUISITES
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# Install OpenLDAP
- name: (007/019) - ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡  Install OpenLDAP
  include_tasks: 21_addons-ldap.yaml
  when: current_ibmaiops_feature.install_ldap == true



# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# INSTALL CONCERT
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
- name: (008/019) - ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡ Install IBM Concert Prerequisites 
  include_tasks: 05_concert-prerequisites.yaml
      
- name: (009/019) - ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡ Install IBM Concert  
  include_tasks: 10_concert-install.yaml



# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# POSTINSTALL TASKS
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# Register LDAP Users
- name: (010/019) - ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡  Register LDAP Server with IBM Concert
  include_tasks: 25-post-ldap-register.yaml
  when: current_ibmaiops_feature.install_ldap == true and current_ibmaiops_feature.ldap_register == true

- name: (011/019) - ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡  Integrate OpenShift Login with OpenLDAP
  include_tasks: 90_integrate-ocp-openldap.yaml
  when: current_ibmaiops_feature.integrate_ocp_openldap | default(false) == true  

- name: (012/019) - ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡  Create Demo UI Openshift WebConsole Additional Menu Item
  include_tasks: 91_addons-concert-create-ocp-tools-menu.yaml
  when: global_config.create_ocp_items | default(true) == true  


# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# INSTALL DEMO CONTENT
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# Install Demo Content
- name: (013/019) - ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡  Install Demo Content
  include_tasks: 30_concert-install-demo-content.yaml
  when: current_ibmaiops_feature.install_demo_content == true | default(false)



- name: (014/019) - ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡ End Logging
  include_tasks: "{{role_path}}/../ibm-aiops-global/tasks/91-log-end.yaml"



- name: ðŸŸ£ðŸŸ£ðŸŸ£ðŸŸ£ðŸŸ£ðŸŸ£  âœ… INSTALLATION MODULE DONE - {{current_ibmaiops_feature.kind}}
  debug: 
    msg: 
    - "***************************************************************************************************************************************************"
    - "***************************************************************************************************************************************************"
    - "***************************************************************************************************************************************************"
    - "***************************************************************************************************************************************************"
    - "                                                                                                                                                   "
    - "       âœ… IBM AIOps - DONE INSTALLING {{current_ibmaiops_feature.kind}}                                                                                 "
    - "                                                                                                                                                   "
    - "***************************************************************************************************************************************************"
    - "***************************************************************************************************************************************************"
    - "***************************************************************************************************************************************************"


- name:   ðŸš€ IBM Concert -  LOGINS
  shell: |
    cd  /tmp/concert/ibm-concert
    echo ""
    echo ""
    echo ""
    echo ""
    echo "------------------------------------------------------------------------------------------------------------------------------"
    echo " ðŸš€ Set Variables"
    echo "------------------------------------------------------------------------------------------------------------------------------"
    export PROD_REGISTRY={{current_ibmaiops_feature.prod_registry}}
    export PROD_USER={{current_ibmaiops_feature.prod_user}}
    export PRIVATE_REGISTRY_LOCATION={{current_ibmaiops_feature.private_registry_location}}
    export DOCKER_EXE=podman 
    export WORK_DIR=$(pwd)
    export PROJECT_OPERATOR={{current_ibmaiops_feature.project_operator}} 
    export PROJECT_INSTANCE={{current_ibmaiops_feature.project_instance}}
    export STG_CLASS_BLOCK={{ AIOPS_STORAGE_CLASS_FILE }}
    export STG_CLASS_FILE={{ AIOPS_STORAGE_CLASS_LARGE_BLOCK }}


    echo ""
    echo ""
    echo ""
    echo ""
    echo "------------------------------------------------------------------------------------------------------------------------------"
    echo " âœ… LOGINS"
    echo "------------------------------------------------------------------------------------------------------------------------------"
    ./ibm-concert-manage.sh get-concert-instance-details

    export OCP_URL=$(oc get Infrastructure cluster -o jsonpath={.status.apiServerURL})
    export OCP_TOKEN=$(oc -n openshift-authentication get secret $(oc get secret -n openshift-authentication |grep -m1 oauth-openshift-token|awk '{print$1}') -o jsonpath='{.data.token}'|base64 --decode)
    echo "            ðŸŒ URL:               $OCP_URL"
    echo "            ðŸ«… User:              kubeadmin"
    echo "            ðŸ” Token:             $OCP_TOKEN"
  register: output_string
  ignore_errors: true
  args:
    executable: /bin/bash

- name: (012/019) - ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡  IBM Concert LOGINS
  debug: 
    var: output_string.stdout_lines
    #verbosity: 1




