

#-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#         ________  __  ___     ___    ________       
#        /  _/ __ )/  |/  /    /   |  /  _/ __ \____  _____
#        / // __  / /|_/ /    / /| |  / // / / / __ \/ ___/
#      _/ // /_/ / /  / /    / ___ |_/ // /_/ / /_/ (__  ) 
#     /___/_____/_/  /_/    /_/  |_/___/\____/ .___/____/  
#                                           /_/
#-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#---------------------------------------------------------------------------------------------------------------------------------------------------"
#  Installing IBM Concert
#
#  IBM Concert
#
#  Â©2024 nikh@ch.ibm.com
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# Installs:
#
#  - IBM Concert
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
 


- name: ðŸŸ£ðŸŸ£ðŸŸ£ðŸŸ£ðŸŸ£ðŸŸ£  INSTALLATION MODULE START - {{current_ibmaiops_feature.kind}}
  debug: 
    msg: 
    - "***************************************************************************************************************************************************"
    - "***************************************************************************************************************************************************"
    - "***************************************************************************************************************************************************"
    - "***************************************************************************************************************************************************"
    - "                                                                                                                                                   "
    - "      ï¿½ IBM AIOps - INSTALLING {{current_ibmaiops_feature.kind}} "
    - "                                                                                                                                                   "
    - "***************************************************************************************************************************************************"
    - "***************************************************************************************************************************************************"
    - "***************************************************************************************************************************************************"


- name: Log
  shell: |
    export MESSAGE="Installing IBM AIOps"
    export currentDate=$(date +%Y-%m-%d_%H:%M)
    echo "---------------------------------------------------------------------------------------------------------------------------------------------------" >> ../install_{{current_ibmaiops_feature.kind}}.log
    echo $currentDate" - "$MESSAGE  >> ../install_{{current_ibmaiops_feature.kind}}.log
  ignore_errors: true



- name: ðŸ“£ OCP CONSOLE - Create Openshift NOTIFICATION
  shell: |
    export AIOPS_NAMESPACE=$(oc get po -A|grep aiops-orchestrator-controller |awk '{print$1}')
    appURL=$(oc get routes -n $AIOPS_NAMESPACE-demo-ui ibm-aiops-demo-ui  -o jsonpath="{['spec']['host']}")|| true
    OPENSHIFT_ROUTE=$(oc get route -n openshift-console console -o jsonpath={.spec.host})
    INSTALL_POD=$(oc get po -n ibm-aiops-installer -l app=ibm-aiops-concert --no-headers|grep "Running"|grep "1/1"|awk '{print$1}')

    cat <<EOF | oc apply -f -
    apiVersion: console.openshift.io/v1
    kind: ConsoleNotification
    metadata:
      name: ibm-aiops-notification-main
    spec:
      backgroundColor: '#141a6b'
      color: '#fff'
      location: {{global_config.position_final_ocp_notification | default("BannerTop")}}
      text: 'Installing  {{current_ibmaiops_feature.kind}} ' 
      link:
          href: "https://$OPENSHIFT_ROUTE/k8s/ns/ibm-aiops-installer/pods/$INSTALL_POD/logs"
          text: Open Logs   
    EOF
  ignore_errors: true
  args:
    executable: /bin/bash



- name:  ðŸŸ¡ðŸŸ¡ðŸŸ¡ INITIALIZATION - Installation Parameters ðŸŸ¡ðŸŸ¡ðŸŸ¡"
  debug:
    msg:
    - "***********************************************************************************************"
    - " ðŸš€ Installing {{current_ibmaiops_feature.kind}}"
    - "***********************************************************************************************"
    - "-----------------------------------------------------------------------------------------------"
    - "  ðŸ“¥ STORAGE"
    - "     ðŸ’¾ Installation Options for SPECIFIC MODULE {{ current_ibmaiops_feature.kind}}"
    - "        Storage Class File Override:             {{ current_ibmaiops_feature.storage_class_file | default('no override') }}"
    - "        Storage Class Block Override:            {{ current_ibmaiops_feature.storage_class_block | default('no override') }}"
    - ""
    - "     ðŸ’¾ Installation Options from GLOBAL"
    - "        Storage Class File Override:             {{ ocp_storage_class_file | default('not defined') }}"
    - "        Storage Class Block Override:            {{ ocp_storage_class_block | default('not defined') }}"
    - "-----------------------------------------------------------------------------------------------"
    - "  ðŸ“¥ CONFIG"
    - "     âœ… Installation Name:                        {{current_ibmaiops_feature.aiops_name}}"
    - "     ðŸ”Ž IBM AIOps Namespace:                      {{current_ibmaiops_feature.project}}"
    - "     ðŸ“£ IBM Concert prod_registry:                {{current_ibmaiops_feature.registry.prod_registry| default('not defined')}}"
    - "     ðŸ“£ IBM Concert prod_user:                    {{current_ibmaiops_feature.registry.prod_user| default('not defined')}}"
    - "     ðŸ“£ IBM Concert private_registry_location:    {{current_ibmaiops_feature.registry.private_registry_location| default('not defined')}}"
    - "     ðŸ“£ IBM Concert project_operator:             {{current_ibmaiops_feature.project.project_operator| default('not defined')}}"
    - "     ðŸ“£ IBM Concert project_instance:             {{current_ibmaiops_feature.project.project_instance| default('not defined')}}"
    - "     ðŸ“£ IBM Concert docker_exe:                   {{current_ibmaiops_feature.installation.docker_exe| default('not defined')}}"
    - "-----------------------------------------------------------------------------------------------"
    - "***********************************************************************************************"




- name: ðŸŸ£ Installing {{current_ibmaiops_feature.kind}} with the following configuration
  debug:
    var: current_ibmaiops_feature

# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# INITIALIZATION
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# Placeholder for customization
- name: (001/019) - ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡ Initialize Custom Hook
  include_tasks: 00_init-custom-hook.yaml

# Initialize Logging
- name: (002/019) - ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡ Initialize Logging
  include_tasks: "{{role_path}}/../ibm-aiops-global/tasks/01_init-logging.yaml"
    
- name: (003/019) - ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡ Initialization Checks
  include_tasks: 02_init_checks.yaml
# Start block
- name: (004/019) - ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡ Start Logging
  include_tasks: "{{role_path}}/../ibm-aiops-global/tasks/90-log-start.yaml"

# Run Prerequisites
- name: (005/019) - ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡ Initialization of the Installation
  include_tasks: 03_init-initialization.yaml



- name: (006/019) - ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡ Get Storage Classes
  include_tasks: "{{role_path}}/../ibm-aiops-global/tasks/05_init-get-storage-class.yaml"


- name: (007/019) - ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡ Install IBM AIOps Prerequisites 
  include_tasks: 05_concert-prerequisites.yaml
      


# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# INSTALL CATALOG with YAML FILE
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
- name: (009/019) - ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡ Install IBM AIOps Catalog - Classic Way (skipped if CASE selected)
  include_tasks: 10_ibm-aiops-catalog.yaml
  when: current_ibmaiops_feature.case_install==false


# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# INSTALL CATALOG with CASE FILE
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
- name: (010/019) - ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡ Install IBM AIOps Catalog - Save Case File (this can take some time - skipped if not selected)
  include_role:
    name: ibm-aiops-case-save
  when: current_ibmaiops_feature.case_install==true


- name: (011/019) - ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡ Install IBM AIOps Catalog - Create CatalogSources from Case File (this can take some time - skipped if not selected)
  include_role:
    name: ibm-aiops-case-catalog-source
  when: current_ibmaiops_feature.case_install==true



# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# INSTALL IBM AIOPS PREREQUISITES
# ---------------------------------------------------------------------------------------------------------------------------------------------------"

# Install IBM AIOPS Prerequisites
- name: (012/019) - ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡ Install the IBM AIOps Instance
  include_tasks: 18_ibm-aiops-install-prerequisites.yaml


# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# INSTALL IBM AIOPS OPERATOR
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
- name: (013/019) - ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡ Install the IBM AIOps Operator
  include_tasks: 11_ibm-aiops-operator.yaml


# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# INSTALL FEATURE FLAGS
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# Install  Feature Flags
- name: (014/019) - ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡  Install IBM AIOPS Feature Flags
  include_tasks: 12_ibm-aiops-featureflags.yaml
  when: current_ibmaiops_feature.install_feature_flags == true | default('false')



# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# INSTALL IBM AIOPS
# ---------------------------------------------------------------------------------------------------------------------------------------------------"

# Install IBM AIOPS Instance
- name: (015/019) - ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡ Install the IBM AIOps Instance
  include_tasks: 19_ibm-aiops-install.yaml
      

# # ---------------------------------------------------------------------------------------------------------------------------------------------------"
# # WAIT FOR IBM AIOPS HACK
# # ---------------------------------------------------------------------------------------------------------------------------------------------------"

# # Wait for IBM AIOPS HACK
# - name: (016/019) - ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡ Wait for IBM AIOps to apply HACK
#   include_tasks: 99_ibm-aiops-wait-ibm-HACK.yaml


# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# WAIT FOR IBM AIOPS
# ---------------------------------------------------------------------------------------------------------------------------------------------------"

# Wait for IBM AIOPS being completely installed
- name: (016/019) - ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡ Wait for IBM AIOps to be ready
  include_tasks: 99_ibm-aiops-wait-ibm-aiops.yaml

# --------------------------------------------------------------------------------------------------------------------------------------
# Create Openshift WebConsole Menu Item
# --------------------------------------------------------------------------------------------------------------------------------------
- name: (017/019) - ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡  Create IBM AIOps Openshift WebConsole Menu Item
  include_tasks: 91_ibm-aiops-create-ocp-menu.yaml
  when: global_config.create_ocp_items | default(true) == true  

# Update IBM AIOps Cards
- name: (018/019) - ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡ Update IBM AIOps Cards
  include_tasks: "{{role_path}}/../ibm-aiops-global/tasks/99_update_cards.yaml"


- name: (019/019) - ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡ðŸŸ¡ End Logging
  include_tasks: "{{role_path}}/../ibm-aiops-global/tasks/91-log-end.yaml"



- name: ðŸŸ£ðŸŸ£ðŸŸ£ðŸŸ£ðŸŸ£ðŸŸ£  âœ… INSTALLATION MODULE DONE - {{current_ibmaiops_feature.kind}}
  debug: 
    msg: 
    - "***************************************************************************************************************************************************"
    - "***************************************************************************************************************************************************"
    - "***************************************************************************************************************************************************"
    - "***************************************************************************************************************************************************"
    - "                                                                                                                                                   "
    - "       âœ… IBM AIOps - DONE INSTALLING {{current_ibmaiops_feature.kind}}                                                                                 "
    - "                                                                                                                                                   "
    - "***************************************************************************************************************************************************"
    - "***************************************************************************************************************************************************"
    - "***************************************************************************************************************************************************"
