

# *************************************************************************************************************************************************
# --------------------------------------------------------------------------------------------------------------------------------------
# Wait for Zen in Common Services being ready
# --------------------------------------------------------------------------------------------------------------------------------------
# *************************************************************************************************************************************************



- name: Log
  shell: |
    export MESSAGE=" ğŸŸ£ğŸŸ£ğŸŸ£ğŸŸ£ğŸŸ£ğŸŸ£  Starting {{current_feature.kind}} Install - {{role_name}}"
    export currentDate=$(date +%Y-%m-%d_%H:%M)
    echo "**********************************************************************************************************************************************************" >> ../install_{{current_feature.kind}}.log
    echo "**********************************************************************************************************************************************************" >> ../install_{{current_feature.kind}}.log
    echo $currentDate" - "$MESSAGE  >> ../install_{{current_feature.kind}}.log



  ignore_errors: true


