

# *************************************************************************************************************************************************
# --------------------------------------------------------------------------------------------------------------------------------------
# Open Doc
# --------------------------------------------------------------------------------------------------------------------------------------
# *************************************************************************************************************************************************
- name: Log
  shell: |
    export MESSAGE=" ðŸŒ Open EventManager"
    export currentDate=$(date +%Y-%m-%d_%H:%M)
    echo "---------------------------------------------------------------------------------------------------------------------------------------------------" >> ../install_{{current_feature.kind}}.log
    echo $currentDate" - "$MESSAGE  >> ../install_{{current_feature.kind}}.log
  ignore_errors: true

- name: ðŸ“£ OCP CONSOLE - Create Openshift NOTIFICATION
  shell: |
    cat <<EOF | oc apply -f -
    apiVersion: console.openshift.io/v1
    kind: ConsoleNotification
    metadata:
      name: ibm-aiops-notification
    spec:
      backgroundColor: '#ffd500'
      color: '#000'
      location: {{global_config.position_ocp_notifications | default("BannerTop")}}
      text: 'Installing {{current_feature.kind}} - Open EventManager'    
    EOF
  ignore_errors: true
  args:
    executable: /bin/bash
  when: global_config.create_ocp_notifications | default(true) == true  




- name: ðŸŒ EVENT MANAGER - Get EVENT MANAGER LOGINS
  shell: |
    export ROUTE=$(oc get route -n {{ current_ibm_feature.project }}  evtmanager-ibm-hdm-common-ui -o jsonpath={.spec.host})
    echo ""
    echo "            ðŸŒ URL:           https://$ROUTE"
    echo "            ðŸ§‘ User:          smadmin"
    echo "            ðŸ” Password:      $(oc get secret -n {{ current_ibm_feature.project }}  evtmanager-was-secret -o jsonpath='{.data.WAS_PASSWORD}'| base64 --decode && echo)"
    echo ""
    echo ""
    export URL=https://$ROUTE
    if [ -x "$(command -v open)" ]; then
      open $URL
    else 
      if [ -x "$(command -v firefox)" ]; then
        firefox $URL
      else 
        if [ -x "$(command -v google-chrome)" ]; then
          google-chrome $URL
        fi
      fi
    fi
  ignore_errors: true
  register: LOGINS


- name: ðŸŸ£ EVENT MANAGER - EVENT MANAGER LOGINS
  debug: 
    var: LOGINS.stdout_lines


- name: Log
  shell: |
    export MESSAGE=" ðŸ•¦ Wait for Event Manager to become ready"
    export currentDate=$(date +%Y-%m-%d_%H:%M)
    echo "---------------------------------------------------------------------------------------------------------------------------------------------------" >> ../install_{{current_feature.kind}}.log
    echo "---------------------------------------------------------------------------------------------------------------------------------------------------" >> ../install_{{current_feature.kind}}.log
    echo "      ðŸ“¥ Event Manager"  >> ../install_{{current_feature.kind}}.log
    echo ""  >> ../install_{{current_feature.kind}}.log
    echo "            ðŸŒ URL:           https://$(oc get route -n {{ current_ibm_feature.project }}  evtmanager-ibm-hdm-common-ui -o jsonpath={.spec.host})"  >> ../install_{{current_feature.kind}}.log
    echo "            ðŸ§‘ User:          smadmin"  >> ../install_{{current_feature.kind}}.log
    echo "            ðŸ” Password:      $(oc get secret -n {{ current_ibm_feature.project }}  evtmanager-was-secret -o jsonpath='{.data.WAS_PASSWORD}'| base64 --decode && echo)"  >> ../install_{{current_feature.kind}}.log
    echo "---------------------------------------------------------------------------------------------------------------------------------------------------" >> ../install_{{current_feature.kind}}.log
    echo "---------------------------------------------------------------------------------------------------------------------------------------------------" >> ../install_{{current_feature.kind}}.log

  ignore_errors: true
